import Modulus40.ConstructionLocalData.Prime41

/-!
# Local signature data at the prime 43

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal43 : LocalData where
  prime := 43
  depth := 1
  rays := [⟨43, 1, 0, 1⟩,
    ⟨43, 1, 0, 2⟩,
    ⟨43, 1, 0, 3⟩,
    ⟨43, 1, 0, 4⟩,
    ⟨43, 1, 0, 5⟩,
    ⟨43, 1, 0, 6⟩,
    ⟨43, 1, 0, 7⟩,
    ⟨43, 1, 0, 8⟩,
    ⟨43, 1, 0, 9⟩,
    ⟨43, 1, 0, 10⟩,
    ⟨43, 1, 0, 11⟩,
    ⟨43, 1, 0, 12⟩,
    ⟨43, 1, 0, 13⟩,
    ⟨43, 1, 0, 14⟩,
    ⟨43, 1, 0, 15⟩,
    ⟨43, 1, 0, 16⟩,
    ⟨43, 1, 0, 17⟩,
    ⟨43, 1, 0, 18⟩,
    ⟨43, 1, 0, 19⟩,
    ⟨43, 1, 0, 20⟩,
    ⟨43, 1, 0, 21⟩,
    ⟨43, 1, 0, 22⟩,
    ⟨43, 1, 0, 23⟩,
    ⟨43, 1, 0, 24⟩,
    ⟨43, 1, 0, 25⟩,
    ⟨43, 1, 0, 26⟩,
    ⟨43, 1, 0, 27⟩,
    ⟨43, 1, 0, 28⟩,
    ⟨43, 1, 0, 29⟩,
    ⟨43, 1, 0, 30⟩,
    ⟨43, 1, 0, 31⟩,
    ⟨43, 1, 0, 32⟩,
    ⟨43, 1, 0, 33⟩,
    ⟨43, 1, 0, 34⟩,
    ⟨43, 1, 0, 35⟩,
    ⟨43, 1, 0, 36⟩,
    ⟨43, 1, 0, 37⟩,
    ⟨43, 1, 0, 38⟩,
    ⟨43, 1, 0, 39⟩,
    ⟨43, 1, 0, 40⟩,
    ⟨43, 1, 0, 41⟩,
    ⟨43, 1, 0, 42⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12,
    .ray 1 0 13,
    .ray 1 0 14,
    .ray 1 0 15,
    .ray 1 0 16,
    .ray 1 0 17,
    .ray 1 0 18,
    .ray 1 0 19,
    .ray 1 0 20,
    .ray 1 0 21,
    .ray 1 0 22,
    .ray 1 0 23,
    .ray 1 0 24,
    .ray 1 0 25,
    .ray 1 0 26,
    .ray 1 0 27,
    .ray 1 0 28,
    .ray 1 0 29,
    .ray 1 0 30,
    .ray 1 0 31,
    .ray 1 0 32,
    .ray 1 0 33,
    .ray 1 0 34,
    .ray 1 0 35,
    .ray 1 0 36,
    .ray 1 0 37,
    .ray 1 0 38,
    .ray 1 0 39,
    .ray 1 0 40,
    .ray 1 0 41,
    .ray 1 0 42]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]

def constructionLocal43Centers : List ℤ := [0]

def constructionLocal43Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 86, 129, 172, 215, 258, 301, 344, 387, 430, 473, 516, 559, 602, 645, 688, 731, 774, 817, 860, 903, 946, 989, 1032, 1075, 1118, 1161, 1204, 1247, 1290, 1333, 1376, 1419, 1462, 1505, 1548, 1591, 1634, 1677, 1720, 1763, 1806]

def constructionLocal43Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41]

theorem constructionLocal43_samples_eq :
    compactCanonicalRepresentatives 43 1 constructionLocal43.rays
      constructionLocal43Centers = constructionLocal43Samples := by decide

theorem constructionLocal43_valid : constructionLocal43.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal43
    constructionLocal43Centers constructionLocal43Witnesses
  · decide
  · decide
  · change constructionLocal43.SignatureWitnessesValid
      (compactCanonicalRepresentatives 43 1 constructionLocal43.rays
        constructionLocal43Centers) constructionLocal43Witnesses
    rw [constructionLocal43_samples_eq]
    decide

end Modulus40
