import Modulus40.ConstructionLocalData.Prime2

/-!
# Local signature data at the prime 3

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal3 : LocalData where
  prime := 3
  depth := 4
  rays := [⟨3, 1, 0, 1⟩,
    ⟨3, 1, 0, 2⟩,
    ⟨3, 2, (-2), 1⟩,
    ⟨3, 2, (-2), 2⟩,
    ⟨3, 2, (-1), 1⟩,
    ⟨3, 2, (-1), 2⟩,
    ⟨3, 2, 0, 1⟩,
    ⟨3, 2, 0, 2⟩,
    ⟨3, 3, (-6), 2⟩,
    ⟨3, 3, (-3), 1⟩,
    ⟨3, 3, (-3), 2⟩,
    ⟨3, 3, 0, 1⟩,
    ⟨3, 3, 0, 2⟩,
    ⟨3, 4, (-24), 1⟩,
    ⟨3, 4, (-24), 2⟩,
    ⟨3, 4, (-6), 1⟩]
  coordinates := [.fixed 0 0,
    .fixed 1 0,
    .fixed 1 1,
    .fixed 1 2,
    .fixed 1 3,
    .fixed 2 1,
    .fixed 2 3,
    .fixed 2 4,
    .fixed 2 6,
    .fixed 2 7,
    .fixed 3 3,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 2 (-2) 1,
    .ray 2 (-2) 2,
    .ray 2 (-1) 1,
    .ray 2 (-1) 2,
    .ray 2 0 1,
    .ray 2 0 2,
    .ray 3 (-6) 2,
    .ray 3 (-3) 1,
    .ray 3 (-3) 2,
    .ray 3 0 1,
    .ray 3 0 2,
    .ray 4 (-24) 1,
    .ray 4 (-24) 2,
    .ray 4 (-6) 1]
  representatives := [1, 2, 3, 4, 5, 6, 7, 9, 12, 15, 16, 18, 21, 30]

def constructionLocal3Centers : List ℤ := [(-24), (-6), (-3), (-2), (-1), 0]

def constructionLocal3Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 76, 77, 57, 138, 75, 156, 78, 159, 79, 160, 80, 161, 81, 162]

def constructionLocal3Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 1, 7, 0, 1, 8, 3, 4, 9, 10, 4, 11, 0, 1, 12, 3, 4, 5, 6, 1, 7, 0, 1, 13, 3, 4, 5, 6, 1, 7, 0, 1, 8, 3, 4, 9, 10, 4, 11, 0, 1, 8, 3, 4, 9, 10, 4, 11, 0, 1, 3, 4, 5, 6, 1, 7, 0, 1, 8, 3, 4, 9, 10, 4, 11, 0, 1, 3, 4, 2, 13, 12, 8, 5, 9, 6, 10, 1, 4, 7, 11]

theorem constructionLocal3_samples_eq :
    compactCanonicalRepresentatives 3 4 constructionLocal3.rays
      constructionLocal3Centers = constructionLocal3Samples := by decide

theorem constructionLocal3_valid : constructionLocal3.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal3
    constructionLocal3Centers constructionLocal3Witnesses
  · decide
  · decide
  · change constructionLocal3.SignatureWitnessesValid
      (compactCanonicalRepresentatives 3 4 constructionLocal3.rays
        constructionLocal3Centers) constructionLocal3Witnesses
    rw [constructionLocal3_samples_eq]
    decide

end Modulus40
