import Modulus40.ConstructionLocalData.Prime101

/-!
# Local signature data at the prime 103

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal103 : LocalData where
  prime := 103
  depth := 1
  rays := []
  coordinates := [.fixed 0 0,
    .fixed 1 0,
    .fixed 1 1,
    .fixed 1 2,
    .fixed 1 3,
    .fixed 1 4,
    .fixed 1 5,
    .fixed 1 6,
    .fixed 1 7,
    .fixed 1 8,
    .fixed 1 9,
    .fixed 1 10,
    .fixed 1 11,
    .fixed 1 12,
    .fixed 1 13,
    .fixed 1 14,
    .fixed 1 15,
    .fixed 1 16,
    .fixed 1 17,
    .fixed 1 18,
    .fixed 1 19,
    .fixed 1 20,
    .fixed 1 21,
    .fixed 1 22,
    .fixed 1 23,
    .fixed 1 24,
    .fixed 1 25,
    .fixed 1 26,
    .fixed 1 27,
    .fixed 1 28,
    .fixed 1 29,
    .fixed 1 30,
    .fixed 1 31,
    .fixed 1 32,
    .fixed 1 33,
    .fixed 1 34,
    .fixed 1 35,
    .fixed 1 36,
    .fixed 1 37,
    .fixed 1 38,
    .fixed 1 39,
    .fixed 1 40,
    .fixed 1 41,
    .fixed 1 42,
    .fixed 1 43,
    .fixed 1 44,
    .fixed 1 45,
    .fixed 1 46,
    .fixed 1 47,
    .fixed 1 48,
    .fixed 1 49,
    .fixed 1 50,
    .fixed 1 51,
    .fixed 1 52,
    .fixed 1 53,
    .fixed 1 54,
    .fixed 1 55,
    .fixed 1 56,
    .fixed 1 57,
    .fixed 1 58,
    .fixed 1 59,
    .fixed 1 60,
    .fixed 1 61,
    .fixed 1 62,
    .fixed 1 63,
    .fixed 1 64,
    .fixed 1 65,
    .fixed 1 66,
    .fixed 1 67,
    .fixed 1 68,
    .fixed 1 69,
    .fixed 1 70,
    .fixed 1 71,
    .fixed 1 72,
    .fixed 1 73,
    .fixed 1 74,
    .fixed 1 75,
    .fixed 1 76,
    .fixed 1 77,
    .fixed 1 78,
    .fixed 1 79,
    .fixed 1 80,
    .fixed 1 81,
    .fixed 1 82,
    .fixed 1 83,
    .fixed 1 84,
    .fixed 1 85,
    .fixed 1 86,
    .fixed 1 87,
    .fixed 1 88,
    .fixed 1 89,
    .fixed 1 90,
    .fixed 1 91,
    .fixed 1 92,
    .fixed 1 93,
    .fixed 1 94,
    .fixed 1 95,
    .fixed 1 96,
    .fixed 1 97,
    .fixed 1 98,
    .fixed 1 99,
    .fixed 1 100,
    .fixed 1 101,
    .fixed 1 102]
  representatives := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102]

def constructionLocal103Centers : List ℤ := []

def constructionLocal103Samples : List ℤ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102]

def constructionLocal103Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102]

theorem constructionLocal103_samples_eq :
    compactCanonicalRepresentatives 103 1 constructionLocal103.rays
      constructionLocal103Centers = constructionLocal103Samples := by decide

theorem constructionLocal103_valid : constructionLocal103.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal103
    constructionLocal103Centers constructionLocal103Witnesses
  · decide
  · decide
  · change constructionLocal103.SignatureWitnessesValid
      (compactCanonicalRepresentatives 103 1 constructionLocal103.rays
        constructionLocal103Centers) constructionLocal103Witnesses
    rw [constructionLocal103_samples_eq]
    decide

end Modulus40
