import Modulus40.ConstructionLocalData.Prime43

/-!
# Local signature data at the prime 47

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal47 : LocalData where
  prime := 47
  depth := 1
  rays := [⟨47, 1, 0, 1⟩,
    ⟨47, 1, 0, 2⟩,
    ⟨47, 1, 0, 3⟩,
    ⟨47, 1, 0, 4⟩,
    ⟨47, 1, 0, 5⟩,
    ⟨47, 1, 0, 6⟩,
    ⟨47, 1, 0, 7⟩,
    ⟨47, 1, 0, 8⟩,
    ⟨47, 1, 0, 9⟩,
    ⟨47, 1, 0, 10⟩,
    ⟨47, 1, 0, 11⟩,
    ⟨47, 1, 0, 12⟩,
    ⟨47, 1, 0, 13⟩,
    ⟨47, 1, 0, 14⟩,
    ⟨47, 1, 0, 15⟩,
    ⟨47, 1, 0, 16⟩,
    ⟨47, 1, 0, 17⟩,
    ⟨47, 1, 0, 18⟩,
    ⟨47, 1, 0, 19⟩,
    ⟨47, 1, 0, 20⟩,
    ⟨47, 1, 0, 21⟩,
    ⟨47, 1, 0, 22⟩,
    ⟨47, 1, 0, 23⟩,
    ⟨47, 1, 0, 24⟩,
    ⟨47, 1, 0, 25⟩,
    ⟨47, 1, 0, 26⟩,
    ⟨47, 1, 0, 27⟩,
    ⟨47, 1, 0, 28⟩,
    ⟨47, 1, 0, 29⟩,
    ⟨47, 1, 0, 30⟩,
    ⟨47, 1, 0, 31⟩,
    ⟨47, 1, 0, 32⟩,
    ⟨47, 1, 0, 33⟩,
    ⟨47, 1, 0, 34⟩,
    ⟨47, 1, 0, 35⟩,
    ⟨47, 1, 0, 36⟩,
    ⟨47, 1, 0, 37⟩,
    ⟨47, 1, 0, 38⟩,
    ⟨47, 1, 0, 39⟩,
    ⟨47, 1, 0, 40⟩,
    ⟨47, 1, 0, 41⟩,
    ⟨47, 1, 0, 42⟩,
    ⟨47, 1, 0, 43⟩,
    ⟨47, 1, 0, 44⟩,
    ⟨47, 1, 0, 45⟩,
    ⟨47, 1, 0, 46⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12,
    .ray 1 0 13,
    .ray 1 0 14,
    .ray 1 0 15,
    .ray 1 0 16,
    .ray 1 0 17,
    .ray 1 0 18,
    .ray 1 0 19,
    .ray 1 0 20,
    .ray 1 0 21,
    .ray 1 0 22,
    .ray 1 0 23,
    .ray 1 0 24,
    .ray 1 0 25,
    .ray 1 0 26,
    .ray 1 0 27,
    .ray 1 0 28,
    .ray 1 0 29,
    .ray 1 0 30,
    .ray 1 0 31,
    .ray 1 0 32,
    .ray 1 0 33,
    .ray 1 0 34,
    .ray 1 0 35,
    .ray 1 0 36,
    .ray 1 0 37,
    .ray 1 0 38,
    .ray 1 0 39,
    .ray 1 0 40,
    .ray 1 0 41,
    .ray 1 0 42,
    .ray 1 0 43,
    .ray 1 0 44,
    .ray 1 0 45,
    .ray 1 0 46]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46]

def constructionLocal47Centers : List ℤ := [0]

def constructionLocal47Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 94, 141, 188, 235, 282, 329, 376, 423, 470, 517, 564, 611, 658, 705, 752, 799, 846, 893, 940, 987, 1034, 1081, 1128, 1175, 1222, 1269, 1316, 1363, 1410, 1457, 1504, 1551, 1598, 1645, 1692, 1739, 1786, 1833, 1880, 1927, 1974, 2021, 2068, 2115, 2162]

def constructionLocal47Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]

theorem constructionLocal47_samples_eq :
    compactCanonicalRepresentatives 47 1 constructionLocal47.rays
      constructionLocal47Centers = constructionLocal47Samples := by decide

theorem constructionLocal47_valid : constructionLocal47.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal47
    constructionLocal47Centers constructionLocal47Witnesses
  · decide
  · decide
  · change constructionLocal47.SignatureWitnessesValid
      (compactCanonicalRepresentatives 47 1 constructionLocal47.rays
        constructionLocal47Centers) constructionLocal47Witnesses
    rw [constructionLocal47_samples_eq]
    decide

end Modulus40
