import Modulus40.ConstructionLocalData.Prime7

/-!
# Local signature data at the prime 11

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal11 : LocalData where
  prime := 11
  depth := 1
  rays := [⟨11, 1, 0, 1⟩,
    ⟨11, 1, 0, 2⟩,
    ⟨11, 1, 0, 3⟩,
    ⟨11, 1, 0, 4⟩,
    ⟨11, 1, 0, 5⟩,
    ⟨11, 1, 0, 6⟩,
    ⟨11, 1, 0, 7⟩,
    ⟨11, 1, 0, 8⟩,
    ⟨11, 1, 0, 9⟩,
    ⟨11, 1, 0, 10⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

def constructionLocal11Centers : List ℤ := [0]

def constructionLocal11Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 22, 33, 44, 55, 66, 77, 88, 99, 110]

def constructionLocal11Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

theorem constructionLocal11_samples_eq :
    compactCanonicalRepresentatives 11 1 constructionLocal11.rays
      constructionLocal11Centers = constructionLocal11Samples := by decide

theorem constructionLocal11_valid : constructionLocal11.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal11
    constructionLocal11Centers constructionLocal11Witnesses
  · decide
  · decide
  · change constructionLocal11.SignatureWitnessesValid
      (compactCanonicalRepresentatives 11 1 constructionLocal11.rays
        constructionLocal11Centers) constructionLocal11Witnesses
    rw [constructionLocal11_samples_eq]
    decide

end Modulus40
