import Modulus40.ConstructionLocalData.Prime61

/-!
# Local signature data at the prime 67

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal67 : LocalData where
  prime := 67
  depth := 1
  rays := [⟨67, 1, 0, 1⟩,
    ⟨67, 1, 0, 2⟩,
    ⟨67, 1, 0, 3⟩,
    ⟨67, 1, 0, 4⟩,
    ⟨67, 1, 0, 5⟩,
    ⟨67, 1, 0, 6⟩,
    ⟨67, 1, 0, 7⟩,
    ⟨67, 1, 0, 8⟩,
    ⟨67, 1, 0, 9⟩,
    ⟨67, 1, 0, 10⟩,
    ⟨67, 1, 0, 11⟩,
    ⟨67, 1, 0, 12⟩,
    ⟨67, 1, 0, 13⟩,
    ⟨67, 1, 0, 14⟩,
    ⟨67, 1, 0, 15⟩,
    ⟨67, 1, 0, 16⟩,
    ⟨67, 1, 0, 17⟩,
    ⟨67, 1, 0, 18⟩,
    ⟨67, 1, 0, 19⟩,
    ⟨67, 1, 0, 20⟩,
    ⟨67, 1, 0, 21⟩,
    ⟨67, 1, 0, 22⟩,
    ⟨67, 1, 0, 23⟩,
    ⟨67, 1, 0, 24⟩,
    ⟨67, 1, 0, 25⟩,
    ⟨67, 1, 0, 26⟩,
    ⟨67, 1, 0, 27⟩,
    ⟨67, 1, 0, 28⟩,
    ⟨67, 1, 0, 29⟩,
    ⟨67, 1, 0, 30⟩,
    ⟨67, 1, 0, 31⟩,
    ⟨67, 1, 0, 32⟩,
    ⟨67, 1, 0, 33⟩,
    ⟨67, 1, 0, 34⟩,
    ⟨67, 1, 0, 35⟩,
    ⟨67, 1, 0, 36⟩,
    ⟨67, 1, 0, 37⟩,
    ⟨67, 1, 0, 38⟩,
    ⟨67, 1, 0, 39⟩,
    ⟨67, 1, 0, 40⟩,
    ⟨67, 1, 0, 41⟩,
    ⟨67, 1, 0, 42⟩,
    ⟨67, 1, 0, 43⟩,
    ⟨67, 1, 0, 44⟩,
    ⟨67, 1, 0, 45⟩,
    ⟨67, 1, 0, 46⟩,
    ⟨67, 1, 0, 47⟩,
    ⟨67, 1, 0, 48⟩,
    ⟨67, 1, 0, 49⟩,
    ⟨67, 1, 0, 50⟩,
    ⟨67, 1, 0, 51⟩,
    ⟨67, 1, 0, 52⟩,
    ⟨67, 1, 0, 53⟩,
    ⟨67, 1, 0, 54⟩,
    ⟨67, 1, 0, 55⟩,
    ⟨67, 1, 0, 56⟩,
    ⟨67, 1, 0, 57⟩,
    ⟨67, 1, 0, 58⟩,
    ⟨67, 1, 0, 59⟩,
    ⟨67, 1, 0, 60⟩,
    ⟨67, 1, 0, 61⟩,
    ⟨67, 1, 0, 62⟩,
    ⟨67, 1, 0, 63⟩,
    ⟨67, 1, 0, 64⟩,
    ⟨67, 1, 0, 65⟩,
    ⟨67, 1, 0, 66⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12,
    .ray 1 0 13,
    .ray 1 0 14,
    .ray 1 0 15,
    .ray 1 0 16,
    .ray 1 0 17,
    .ray 1 0 18,
    .ray 1 0 19,
    .ray 1 0 20,
    .ray 1 0 21,
    .ray 1 0 22,
    .ray 1 0 23,
    .ray 1 0 24,
    .ray 1 0 25,
    .ray 1 0 26,
    .ray 1 0 27,
    .ray 1 0 28,
    .ray 1 0 29,
    .ray 1 0 30,
    .ray 1 0 31,
    .ray 1 0 32,
    .ray 1 0 33,
    .ray 1 0 34,
    .ray 1 0 35,
    .ray 1 0 36,
    .ray 1 0 37,
    .ray 1 0 38,
    .ray 1 0 39,
    .ray 1 0 40,
    .ray 1 0 41,
    .ray 1 0 42,
    .ray 1 0 43,
    .ray 1 0 44,
    .ray 1 0 45,
    .ray 1 0 46,
    .ray 1 0 47,
    .ray 1 0 48,
    .ray 1 0 49,
    .ray 1 0 50,
    .ray 1 0 51,
    .ray 1 0 52,
    .ray 1 0 53,
    .ray 1 0 54,
    .ray 1 0 55,
    .ray 1 0 56,
    .ray 1 0 57,
    .ray 1 0 58,
    .ray 1 0 59,
    .ray 1 0 60,
    .ray 1 0 61,
    .ray 1 0 62,
    .ray 1 0 63,
    .ray 1 0 64,
    .ray 1 0 65,
    .ray 1 0 66]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]

def constructionLocal67Centers : List ℤ := [0]

def constructionLocal67Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 134, 201, 268, 335, 402, 469, 536, 603, 670, 737, 804, 871, 938, 1005, 1072, 1139, 1206, 1273, 1340, 1407, 1474, 1541, 1608, 1675, 1742, 1809, 1876, 1943, 2010, 2077, 2144, 2211, 2278, 2345, 2412, 2479, 2546, 2613, 2680, 2747, 2814, 2881, 2948, 3015, 3082, 3149, 3216, 3283, 3350, 3417, 3484, 3551, 3618, 3685, 3752, 3819, 3886, 3953, 4020, 4087, 4154, 4221, 4288, 4355, 4422]

def constructionLocal67Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]

theorem constructionLocal67_samples_eq :
    compactCanonicalRepresentatives 67 1 constructionLocal67.rays
      constructionLocal67Centers = constructionLocal67Samples := by decide

theorem constructionLocal67_valid : constructionLocal67.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal67
    constructionLocal67Centers constructionLocal67Witnesses
  · decide
  · decide
  · change constructionLocal67.SignatureWitnessesValid
      (compactCanonicalRepresentatives 67 1 constructionLocal67.rays
        constructionLocal67Centers) constructionLocal67Witnesses
    rw [constructionLocal67_samples_eq]
    decide

end Modulus40
