import Modulus40.ConstructionLocalData.Prime19

/-!
# Local signature data at the prime 23

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal23 : LocalData where
  prime := 23
  depth := 1
  rays := [⟨23, 1, 0, 1⟩,
    ⟨23, 1, 0, 2⟩,
    ⟨23, 1, 0, 3⟩,
    ⟨23, 1, 0, 4⟩,
    ⟨23, 1, 0, 5⟩,
    ⟨23, 1, 0, 6⟩,
    ⟨23, 1, 0, 7⟩,
    ⟨23, 1, 0, 8⟩,
    ⟨23, 1, 0, 9⟩,
    ⟨23, 1, 0, 10⟩,
    ⟨23, 1, 0, 11⟩,
    ⟨23, 1, 0, 12⟩,
    ⟨23, 1, 0, 13⟩,
    ⟨23, 1, 0, 14⟩,
    ⟨23, 1, 0, 15⟩,
    ⟨23, 1, 0, 16⟩,
    ⟨23, 1, 0, 17⟩,
    ⟨23, 1, 0, 18⟩,
    ⟨23, 1, 0, 19⟩,
    ⟨23, 1, 0, 20⟩,
    ⟨23, 1, 0, 21⟩,
    ⟨23, 1, 0, 22⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12,
    .ray 1 0 13,
    .ray 1 0 14,
    .ray 1 0 15,
    .ray 1 0 16,
    .ray 1 0 17,
    .ray 1 0 18,
    .ray 1 0 19,
    .ray 1 0 20,
    .ray 1 0 21,
    .ray 1 0 22]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

def constructionLocal23Centers : List ℤ := [0]

def constructionLocal23Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 46, 69, 92, 115, 138, 161, 184, 207, 230, 253, 276, 299, 322, 345, 368, 391, 414, 437, 460, 483, 506]

def constructionLocal23Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

theorem constructionLocal23_samples_eq :
    compactCanonicalRepresentatives 23 1 constructionLocal23.rays
      constructionLocal23Centers = constructionLocal23Samples := by decide

theorem constructionLocal23_valid : constructionLocal23.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal23
    constructionLocal23Centers constructionLocal23Witnesses
  · decide
  · decide
  · change constructionLocal23.SignatureWitnessesValid
      (compactCanonicalRepresentatives 23 1 constructionLocal23.rays
        constructionLocal23Centers) constructionLocal23Witnesses
    rw [constructionLocal23_samples_eq]
    decide

end Modulus40
