import Modulus40.ConstructionLocalData.Prime53

/-!
# Local signature data at the prime 59

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal59 : LocalData where
  prime := 59
  depth := 1
  rays := [⟨59, 1, 0, 1⟩,
    ⟨59, 1, 0, 2⟩,
    ⟨59, 1, 0, 3⟩,
    ⟨59, 1, 0, 4⟩,
    ⟨59, 1, 0, 5⟩,
    ⟨59, 1, 0, 6⟩,
    ⟨59, 1, 0, 7⟩,
    ⟨59, 1, 0, 8⟩,
    ⟨59, 1, 0, 9⟩,
    ⟨59, 1, 0, 10⟩,
    ⟨59, 1, 0, 11⟩,
    ⟨59, 1, 0, 12⟩,
    ⟨59, 1, 0, 13⟩,
    ⟨59, 1, 0, 14⟩,
    ⟨59, 1, 0, 15⟩,
    ⟨59, 1, 0, 16⟩,
    ⟨59, 1, 0, 17⟩,
    ⟨59, 1, 0, 18⟩,
    ⟨59, 1, 0, 19⟩,
    ⟨59, 1, 0, 20⟩,
    ⟨59, 1, 0, 21⟩,
    ⟨59, 1, 0, 22⟩,
    ⟨59, 1, 0, 23⟩,
    ⟨59, 1, 0, 24⟩,
    ⟨59, 1, 0, 25⟩,
    ⟨59, 1, 0, 26⟩,
    ⟨59, 1, 0, 27⟩,
    ⟨59, 1, 0, 28⟩,
    ⟨59, 1, 0, 29⟩,
    ⟨59, 1, 0, 30⟩,
    ⟨59, 1, 0, 31⟩,
    ⟨59, 1, 0, 32⟩,
    ⟨59, 1, 0, 33⟩,
    ⟨59, 1, 0, 34⟩,
    ⟨59, 1, 0, 35⟩,
    ⟨59, 1, 0, 36⟩,
    ⟨59, 1, 0, 37⟩,
    ⟨59, 1, 0, 38⟩,
    ⟨59, 1, 0, 39⟩,
    ⟨59, 1, 0, 40⟩,
    ⟨59, 1, 0, 41⟩,
    ⟨59, 1, 0, 42⟩,
    ⟨59, 1, 0, 43⟩,
    ⟨59, 1, 0, 44⟩,
    ⟨59, 1, 0, 45⟩,
    ⟨59, 1, 0, 46⟩,
    ⟨59, 1, 0, 47⟩,
    ⟨59, 1, 0, 48⟩,
    ⟨59, 1, 0, 49⟩,
    ⟨59, 1, 0, 50⟩,
    ⟨59, 1, 0, 51⟩,
    ⟨59, 1, 0, 52⟩,
    ⟨59, 1, 0, 53⟩,
    ⟨59, 1, 0, 54⟩,
    ⟨59, 1, 0, 55⟩,
    ⟨59, 1, 0, 56⟩,
    ⟨59, 1, 0, 57⟩,
    ⟨59, 1, 0, 58⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12,
    .ray 1 0 13,
    .ray 1 0 14,
    .ray 1 0 15,
    .ray 1 0 16,
    .ray 1 0 17,
    .ray 1 0 18,
    .ray 1 0 19,
    .ray 1 0 20,
    .ray 1 0 21,
    .ray 1 0 22,
    .ray 1 0 23,
    .ray 1 0 24,
    .ray 1 0 25,
    .ray 1 0 26,
    .ray 1 0 27,
    .ray 1 0 28,
    .ray 1 0 29,
    .ray 1 0 30,
    .ray 1 0 31,
    .ray 1 0 32,
    .ray 1 0 33,
    .ray 1 0 34,
    .ray 1 0 35,
    .ray 1 0 36,
    .ray 1 0 37,
    .ray 1 0 38,
    .ray 1 0 39,
    .ray 1 0 40,
    .ray 1 0 41,
    .ray 1 0 42,
    .ray 1 0 43,
    .ray 1 0 44,
    .ray 1 0 45,
    .ray 1 0 46,
    .ray 1 0 47,
    .ray 1 0 48,
    .ray 1 0 49,
    .ray 1 0 50,
    .ray 1 0 51,
    .ray 1 0 52,
    .ray 1 0 53,
    .ray 1 0 54,
    .ray 1 0 55,
    .ray 1 0 56,
    .ray 1 0 57,
    .ray 1 0 58]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58]

def constructionLocal59Centers : List ℤ := [0]

def constructionLocal59Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 118, 177, 236, 295, 354, 413, 472, 531, 590, 649, 708, 767, 826, 885, 944, 1003, 1062, 1121, 1180, 1239, 1298, 1357, 1416, 1475, 1534, 1593, 1652, 1711, 1770, 1829, 1888, 1947, 2006, 2065, 2124, 2183, 2242, 2301, 2360, 2419, 2478, 2537, 2596, 2655, 2714, 2773, 2832, 2891, 2950, 3009, 3068, 3127, 3186, 3245, 3304, 3363, 3422]

def constructionLocal59Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57]

theorem constructionLocal59_samples_eq :
    compactCanonicalRepresentatives 59 1 constructionLocal59.rays
      constructionLocal59Centers = constructionLocal59Samples := by decide

theorem constructionLocal59_valid : constructionLocal59.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal59
    constructionLocal59Centers constructionLocal59Witnesses
  · decide
  · decide
  · change constructionLocal59.SignatureWitnessesValid
      (compactCanonicalRepresentatives 59 1 constructionLocal59.rays
        constructionLocal59Centers) constructionLocal59Witnesses
    rw [constructionLocal59_samples_eq]
    decide

end Modulus40
