import Modulus40.ConstructionLocalData.Prime11

/-!
# Local signature data at the prime 13

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal13 : LocalData where
  prime := 13
  depth := 1
  rays := [⟨13, 1, 0, 1⟩,
    ⟨13, 1, 0, 2⟩,
    ⟨13, 1, 0, 3⟩,
    ⟨13, 1, 0, 4⟩,
    ⟨13, 1, 0, 5⟩,
    ⟨13, 1, 0, 6⟩,
    ⟨13, 1, 0, 7⟩,
    ⟨13, 1, 0, 8⟩,
    ⟨13, 1, 0, 9⟩,
    ⟨13, 1, 0, 10⟩,
    ⟨13, 1, 0, 11⟩,
    ⟨13, 1, 0, 12⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

def constructionLocal13Centers : List ℤ := [0]

def constructionLocal13Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 26, 39, 52, 65, 78, 91, 104, 117, 130, 143, 156]

def constructionLocal13Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

theorem constructionLocal13_samples_eq :
    compactCanonicalRepresentatives 13 1 constructionLocal13.rays
      constructionLocal13Centers = constructionLocal13Samples := by decide

theorem constructionLocal13_valid : constructionLocal13.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal13
    constructionLocal13Centers constructionLocal13Witnesses
  · decide
  · decide
  · change constructionLocal13.SignatureWitnessesValid
      (compactCanonicalRepresentatives 13 1 constructionLocal13.rays
        constructionLocal13Centers) constructionLocal13Witnesses
    rw [constructionLocal13_samples_eq]
    decide

end Modulus40
