import Modulus40.ConstructionLocalData.Prime59

/-!
# Local signature data at the prime 61

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal61 : LocalData where
  prime := 61
  depth := 1
  rays := [⟨61, 1, 0, 1⟩,
    ⟨61, 1, 0, 2⟩,
    ⟨61, 1, 0, 3⟩,
    ⟨61, 1, 0, 4⟩,
    ⟨61, 1, 0, 5⟩,
    ⟨61, 1, 0, 6⟩,
    ⟨61, 1, 0, 7⟩,
    ⟨61, 1, 0, 8⟩,
    ⟨61, 1, 0, 9⟩,
    ⟨61, 1, 0, 10⟩,
    ⟨61, 1, 0, 11⟩,
    ⟨61, 1, 0, 12⟩,
    ⟨61, 1, 0, 13⟩,
    ⟨61, 1, 0, 14⟩,
    ⟨61, 1, 0, 15⟩,
    ⟨61, 1, 0, 16⟩,
    ⟨61, 1, 0, 17⟩,
    ⟨61, 1, 0, 18⟩,
    ⟨61, 1, 0, 19⟩,
    ⟨61, 1, 0, 20⟩,
    ⟨61, 1, 0, 21⟩,
    ⟨61, 1, 0, 22⟩,
    ⟨61, 1, 0, 23⟩,
    ⟨61, 1, 0, 24⟩,
    ⟨61, 1, 0, 25⟩,
    ⟨61, 1, 0, 26⟩,
    ⟨61, 1, 0, 27⟩,
    ⟨61, 1, 0, 28⟩,
    ⟨61, 1, 0, 29⟩,
    ⟨61, 1, 0, 30⟩,
    ⟨61, 1, 0, 31⟩,
    ⟨61, 1, 0, 32⟩,
    ⟨61, 1, 0, 33⟩,
    ⟨61, 1, 0, 34⟩,
    ⟨61, 1, 0, 35⟩,
    ⟨61, 1, 0, 36⟩,
    ⟨61, 1, 0, 37⟩,
    ⟨61, 1, 0, 38⟩,
    ⟨61, 1, 0, 39⟩,
    ⟨61, 1, 0, 40⟩,
    ⟨61, 1, 0, 41⟩,
    ⟨61, 1, 0, 42⟩,
    ⟨61, 1, 0, 43⟩,
    ⟨61, 1, 0, 44⟩,
    ⟨61, 1, 0, 45⟩,
    ⟨61, 1, 0, 46⟩,
    ⟨61, 1, 0, 47⟩,
    ⟨61, 1, 0, 48⟩,
    ⟨61, 1, 0, 49⟩,
    ⟨61, 1, 0, 50⟩,
    ⟨61, 1, 0, 51⟩,
    ⟨61, 1, 0, 52⟩,
    ⟨61, 1, 0, 53⟩,
    ⟨61, 1, 0, 54⟩,
    ⟨61, 1, 0, 55⟩,
    ⟨61, 1, 0, 56⟩,
    ⟨61, 1, 0, 57⟩,
    ⟨61, 1, 0, 58⟩,
    ⟨61, 1, 0, 59⟩,
    ⟨61, 1, 0, 60⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12,
    .ray 1 0 13,
    .ray 1 0 14,
    .ray 1 0 15,
    .ray 1 0 16,
    .ray 1 0 17,
    .ray 1 0 18,
    .ray 1 0 19,
    .ray 1 0 20,
    .ray 1 0 21,
    .ray 1 0 22,
    .ray 1 0 23,
    .ray 1 0 24,
    .ray 1 0 25,
    .ray 1 0 26,
    .ray 1 0 27,
    .ray 1 0 28,
    .ray 1 0 29,
    .ray 1 0 30,
    .ray 1 0 31,
    .ray 1 0 32,
    .ray 1 0 33,
    .ray 1 0 34,
    .ray 1 0 35,
    .ray 1 0 36,
    .ray 1 0 37,
    .ray 1 0 38,
    .ray 1 0 39,
    .ray 1 0 40,
    .ray 1 0 41,
    .ray 1 0 42,
    .ray 1 0 43,
    .ray 1 0 44,
    .ray 1 0 45,
    .ray 1 0 46,
    .ray 1 0 47,
    .ray 1 0 48,
    .ray 1 0 49,
    .ray 1 0 50,
    .ray 1 0 51,
    .ray 1 0 52,
    .ray 1 0 53,
    .ray 1 0 54,
    .ray 1 0 55,
    .ray 1 0 56,
    .ray 1 0 57,
    .ray 1 0 58,
    .ray 1 0 59,
    .ray 1 0 60]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]

def constructionLocal61Centers : List ℤ := [0]

def constructionLocal61Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 122, 183, 244, 305, 366, 427, 488, 549, 610, 671, 732, 793, 854, 915, 976, 1037, 1098, 1159, 1220, 1281, 1342, 1403, 1464, 1525, 1586, 1647, 1708, 1769, 1830, 1891, 1952, 2013, 2074, 2135, 2196, 2257, 2318, 2379, 2440, 2501, 2562, 2623, 2684, 2745, 2806, 2867, 2928, 2989, 3050, 3111, 3172, 3233, 3294, 3355, 3416, 3477, 3538, 3599, 3660]

def constructionLocal61Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]

theorem constructionLocal61_samples_eq :
    compactCanonicalRepresentatives 61 1 constructionLocal61.rays
      constructionLocal61Centers = constructionLocal61Samples := by decide

theorem constructionLocal61_valid : constructionLocal61.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal61
    constructionLocal61Centers constructionLocal61Witnesses
  · decide
  · decide
  · change constructionLocal61.SignatureWitnessesValid
      (compactCanonicalRepresentatives 61 1 constructionLocal61.rays
        constructionLocal61Centers) constructionLocal61Witnesses
    rw [constructionLocal61_samples_eq]
    decide

end Modulus40
