import Modulus40.ConstructionLocalData.Prime67

/-!
# Local signature data at the prime 71

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal71 : LocalData where
  prime := 71
  depth := 1
  rays := [⟨71, 1, 0, 1⟩,
    ⟨71, 1, 0, 2⟩,
    ⟨71, 1, 0, 3⟩,
    ⟨71, 1, 0, 4⟩,
    ⟨71, 1, 0, 5⟩,
    ⟨71, 1, 0, 6⟩,
    ⟨71, 1, 0, 7⟩,
    ⟨71, 1, 0, 8⟩,
    ⟨71, 1, 0, 9⟩,
    ⟨71, 1, 0, 10⟩,
    ⟨71, 1, 0, 11⟩,
    ⟨71, 1, 0, 12⟩,
    ⟨71, 1, 0, 13⟩,
    ⟨71, 1, 0, 14⟩,
    ⟨71, 1, 0, 15⟩,
    ⟨71, 1, 0, 16⟩,
    ⟨71, 1, 0, 17⟩,
    ⟨71, 1, 0, 18⟩,
    ⟨71, 1, 0, 19⟩,
    ⟨71, 1, 0, 20⟩,
    ⟨71, 1, 0, 21⟩,
    ⟨71, 1, 0, 22⟩,
    ⟨71, 1, 0, 23⟩,
    ⟨71, 1, 0, 24⟩,
    ⟨71, 1, 0, 25⟩,
    ⟨71, 1, 0, 26⟩,
    ⟨71, 1, 0, 27⟩,
    ⟨71, 1, 0, 28⟩,
    ⟨71, 1, 0, 29⟩,
    ⟨71, 1, 0, 30⟩,
    ⟨71, 1, 0, 31⟩,
    ⟨71, 1, 0, 32⟩,
    ⟨71, 1, 0, 33⟩,
    ⟨71, 1, 0, 34⟩,
    ⟨71, 1, 0, 35⟩,
    ⟨71, 1, 0, 36⟩,
    ⟨71, 1, 0, 37⟩,
    ⟨71, 1, 0, 38⟩,
    ⟨71, 1, 0, 39⟩,
    ⟨71, 1, 0, 40⟩,
    ⟨71, 1, 0, 41⟩,
    ⟨71, 1, 0, 42⟩,
    ⟨71, 1, 0, 43⟩,
    ⟨71, 1, 0, 44⟩,
    ⟨71, 1, 0, 45⟩,
    ⟨71, 1, 0, 46⟩,
    ⟨71, 1, 0, 47⟩,
    ⟨71, 1, 0, 48⟩,
    ⟨71, 1, 0, 49⟩,
    ⟨71, 1, 0, 50⟩,
    ⟨71, 1, 0, 51⟩,
    ⟨71, 1, 0, 52⟩,
    ⟨71, 1, 0, 53⟩,
    ⟨71, 1, 0, 54⟩,
    ⟨71, 1, 0, 55⟩,
    ⟨71, 1, 0, 56⟩,
    ⟨71, 1, 0, 57⟩,
    ⟨71, 1, 0, 58⟩,
    ⟨71, 1, 0, 59⟩,
    ⟨71, 1, 0, 60⟩,
    ⟨71, 1, 0, 61⟩,
    ⟨71, 1, 0, 62⟩,
    ⟨71, 1, 0, 63⟩,
    ⟨71, 1, 0, 64⟩,
    ⟨71, 1, 0, 65⟩,
    ⟨71, 1, 0, 66⟩,
    ⟨71, 1, 0, 67⟩,
    ⟨71, 1, 0, 68⟩,
    ⟨71, 1, 0, 69⟩,
    ⟨71, 1, 0, 70⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12,
    .ray 1 0 13,
    .ray 1 0 14,
    .ray 1 0 15,
    .ray 1 0 16,
    .ray 1 0 17,
    .ray 1 0 18,
    .ray 1 0 19,
    .ray 1 0 20,
    .ray 1 0 21,
    .ray 1 0 22,
    .ray 1 0 23,
    .ray 1 0 24,
    .ray 1 0 25,
    .ray 1 0 26,
    .ray 1 0 27,
    .ray 1 0 28,
    .ray 1 0 29,
    .ray 1 0 30,
    .ray 1 0 31,
    .ray 1 0 32,
    .ray 1 0 33,
    .ray 1 0 34,
    .ray 1 0 35,
    .ray 1 0 36,
    .ray 1 0 37,
    .ray 1 0 38,
    .ray 1 0 39,
    .ray 1 0 40,
    .ray 1 0 41,
    .ray 1 0 42,
    .ray 1 0 43,
    .ray 1 0 44,
    .ray 1 0 45,
    .ray 1 0 46,
    .ray 1 0 47,
    .ray 1 0 48,
    .ray 1 0 49,
    .ray 1 0 50,
    .ray 1 0 51,
    .ray 1 0 52,
    .ray 1 0 53,
    .ray 1 0 54,
    .ray 1 0 55,
    .ray 1 0 56,
    .ray 1 0 57,
    .ray 1 0 58,
    .ray 1 0 59,
    .ray 1 0 60,
    .ray 1 0 61,
    .ray 1 0 62,
    .ray 1 0 63,
    .ray 1 0 64,
    .ray 1 0 65,
    .ray 1 0 66,
    .ray 1 0 67,
    .ray 1 0 68,
    .ray 1 0 69,
    .ray 1 0 70]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70]

def constructionLocal71Centers : List ℤ := [0]

def constructionLocal71Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 142, 213, 284, 355, 426, 497, 568, 639, 710, 781, 852, 923, 994, 1065, 1136, 1207, 1278, 1349, 1420, 1491, 1562, 1633, 1704, 1775, 1846, 1917, 1988, 2059, 2130, 2201, 2272, 2343, 2414, 2485, 2556, 2627, 2698, 2769, 2840, 2911, 2982, 3053, 3124, 3195, 3266, 3337, 3408, 3479, 3550, 3621, 3692, 3763, 3834, 3905, 3976, 4047, 4118, 4189, 4260, 4331, 4402, 4473, 4544, 4615, 4686, 4757, 4828, 4899, 4970]

def constructionLocal71Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]

theorem constructionLocal71_samples_eq :
    compactCanonicalRepresentatives 71 1 constructionLocal71.rays
      constructionLocal71Centers = constructionLocal71Samples := by decide

theorem constructionLocal71_valid : constructionLocal71.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal71
    constructionLocal71Centers constructionLocal71Witnesses
  · decide
  · decide
  · change constructionLocal71.SignatureWitnessesValid
      (compactCanonicalRepresentatives 71 1 constructionLocal71.rays
        constructionLocal71Centers) constructionLocal71Witnesses
    rw [constructionLocal71_samples_eq]
    decide

end Modulus40
