import Modulus40.ConstructionLocalData.Prime23

/-!
# Local signature data at the prime 29

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal29 : LocalData where
  prime := 29
  depth := 1
  rays := [⟨29, 1, 0, 1⟩,
    ⟨29, 1, 0, 2⟩,
    ⟨29, 1, 0, 3⟩,
    ⟨29, 1, 0, 4⟩,
    ⟨29, 1, 0, 5⟩,
    ⟨29, 1, 0, 6⟩,
    ⟨29, 1, 0, 7⟩,
    ⟨29, 1, 0, 8⟩,
    ⟨29, 1, 0, 9⟩,
    ⟨29, 1, 0, 10⟩,
    ⟨29, 1, 0, 11⟩,
    ⟨29, 1, 0, 12⟩,
    ⟨29, 1, 0, 13⟩,
    ⟨29, 1, 0, 14⟩,
    ⟨29, 1, 0, 15⟩,
    ⟨29, 1, 0, 16⟩,
    ⟨29, 1, 0, 17⟩,
    ⟨29, 1, 0, 18⟩,
    ⟨29, 1, 0, 19⟩,
    ⟨29, 1, 0, 20⟩,
    ⟨29, 1, 0, 21⟩,
    ⟨29, 1, 0, 22⟩,
    ⟨29, 1, 0, 23⟩,
    ⟨29, 1, 0, 24⟩,
    ⟨29, 1, 0, 25⟩,
    ⟨29, 1, 0, 26⟩,
    ⟨29, 1, 0, 27⟩,
    ⟨29, 1, 0, 28⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12,
    .ray 1 0 13,
    .ray 1 0 14,
    .ray 1 0 15,
    .ray 1 0 16,
    .ray 1 0 17,
    .ray 1 0 18,
    .ray 1 0 19,
    .ray 1 0 20,
    .ray 1 0 21,
    .ray 1 0 22,
    .ray 1 0 23,
    .ray 1 0 24,
    .ray 1 0 25,
    .ray 1 0 26,
    .ray 1 0 27,
    .ray 1 0 28]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]

def constructionLocal29Centers : List ℤ := [0]

def constructionLocal29Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 58, 87, 116, 145, 174, 203, 232, 261, 290, 319, 348, 377, 406, 435, 464, 493, 522, 551, 580, 609, 638, 667, 696, 725, 754, 783, 812]

def constructionLocal29Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

theorem constructionLocal29_samples_eq :
    compactCanonicalRepresentatives 29 1 constructionLocal29.rays
      constructionLocal29Centers = constructionLocal29Samples := by decide

theorem constructionLocal29_valid : constructionLocal29.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal29
    constructionLocal29Centers constructionLocal29Witnesses
  · decide
  · decide
  · change constructionLocal29.SignatureWitnessesValid
      (compactCanonicalRepresentatives 29 1 constructionLocal29.rays
        constructionLocal29Centers) constructionLocal29Witnesses
    rw [constructionLocal29_samples_eq]
    decide

end Modulus40
