import Modulus40.ConstructionLocalData.Prime3

/-!
# Local signature data at the prime 5

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal5 : LocalData where
  prime := 5
  depth := 3
  rays := [⟨5, 1, 0, 1⟩,
    ⟨5, 1, 0, 2⟩,
    ⟨5, 1, 0, 3⟩,
    ⟨5, 1, 0, 4⟩,
    ⟨5, 2, (-4), 1⟩,
    ⟨5, 2, (-4), 2⟩,
    ⟨5, 2, (-4), 3⟩,
    ⟨5, 2, (-4), 4⟩,
    ⟨5, 2, (-3), 1⟩,
    ⟨5, 2, (-3), 2⟩,
    ⟨5, 2, (-3), 3⟩,
    ⟨5, 2, (-3), 4⟩,
    ⟨5, 2, (-2), 1⟩,
    ⟨5, 2, (-2), 2⟩,
    ⟨5, 2, (-2), 3⟩,
    ⟨5, 2, (-2), 4⟩,
    ⟨5, 2, (-1), 1⟩,
    ⟨5, 2, (-1), 2⟩,
    ⟨5, 2, (-1), 3⟩,
    ⟨5, 2, (-1), 4⟩,
    ⟨5, 2, 0, 1⟩,
    ⟨5, 2, 0, 2⟩,
    ⟨5, 2, 0, 3⟩,
    ⟨5, 2, 0, 4⟩,
    ⟨5, 3, (-5), 1⟩,
    ⟨5, 3, (-5), 2⟩,
    ⟨5, 3, (-5), 3⟩,
    ⟨5, 3, (-5), 4⟩,
    ⟨5, 3, 0, 4⟩]
  coordinates := [.fixed 0 0,
    .fixed 1 1,
    .fixed 1 2,
    .fixed 1 3,
    .fixed 1 4,
    .fixed 2 20,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 2 (-4) 1,
    .ray 2 (-4) 2,
    .ray 2 (-4) 3,
    .ray 2 (-4) 4,
    .ray 2 (-3) 1,
    .ray 2 (-3) 2,
    .ray 2 (-3) 3,
    .ray 2 (-3) 4,
    .ray 2 (-2) 1,
    .ray 2 (-2) 2,
    .ray 2 (-2) 3,
    .ray 2 (-2) 4,
    .ray 2 (-1) 1,
    .ray 2 (-1) 2,
    .ray 2 (-1) 3,
    .ray 2 (-1) 4,
    .ray 2 0 1,
    .ray 2 0 2,
    .ray 2 0 3,
    .ray 2 0 4,
    .ray 3 (-5) 1,
    .ray 3 (-5) 2,
    .ray 3 (-5) 3,
    .ray 3 (-5) 4,
    .ray 3 0 4]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 45, 70, 95, 100]

def constructionLocal5Centers : List ℤ := [(-5), (-4), (-3), (-2), (-1), 0]

def constructionLocal5Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 245, 370, 495, 121, 246, 371, 496, 122, 247, 372, 497, 123, 248, 373, 498, 124, 249, 374, 499, 125, 250, 375, 500]

def constructionLocal5Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22, 15, 16, 17, 18, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 0, 5, 10, 15, 1, 6, 11, 16, 2, 7, 12, 17, 3, 8, 13, 18, 4, 9, 14, 23]

theorem constructionLocal5_samples_eq :
    compactCanonicalRepresentatives 5 3 constructionLocal5.rays
      constructionLocal5Centers = constructionLocal5Samples := by decide

theorem constructionLocal5_valid : constructionLocal5.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal5
    constructionLocal5Centers constructionLocal5Witnesses
  · decide
  · decide
  · change constructionLocal5.SignatureWitnessesValid
      (compactCanonicalRepresentatives 5 3 constructionLocal5.rays
        constructionLocal5Centers) constructionLocal5Witnesses
    rw [constructionLocal5_samples_eq]
    decide

end Modulus40
