import Modulus40.LocalDataChecking

/-!
# Local signature data at the prime 2

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal2 : LocalData where
  prime := 2
  depth := 6
  rays := [⟨2, 2, 0, 1⟩,
    ⟨2, 3, (-3), 1⟩,
    ⟨2, 3, (-2), 1⟩,
    ⟨2, 3, (-1), 1⟩,
    ⟨2, 3, 0, 1⟩,
    ⟨2, 4, (-6), 1⟩,
    ⟨2, 4, (-5), 1⟩,
    ⟨2, 4, (-4), 1⟩,
    ⟨2, 4, (-2), 1⟩,
    ⟨2, 4, (-1), 1⟩,
    ⟨2, 5, (-8), 1⟩,
    ⟨2, 6, (-16), 1⟩,
    ⟨2, 6, 0, 1⟩]
  coordinates := [.fixed 0 0,
    .fixed 1 0,
    .fixed 1 1,
    .fixed 2 0,
    .fixed 2 1,
    .fixed 2 2,
    .fixed 2 3,
    .fixed 3 0,
    .fixed 3 2,
    .fixed 3 3,
    .fixed 3 4,
    .fixed 3 6,
    .fixed 4 8,
    .fixed 5 16,
    .ray 2 0 1,
    .ray 3 (-3) 1,
    .ray 3 (-2) 1,
    .ray 3 (-1) 1,
    .ray 3 0 1,
    .ray 4 (-6) 1,
    .ray 4 (-5) 1,
    .ray 4 (-4) 1,
    .ray 4 (-2) 1,
    .ray 4 (-1) 1,
    .ray 5 (-8) 1,
    .ray 6 (-16) 1,
    .ray 6 0 1]
  representatives := [1, 2, 3, 4, 6, 7, 8, 16, 32]

def constructionLocal2Centers : List ℤ := [(-16), (-8), (-6), (-5), (-4), (-3), (-2), (-1), 0]

def constructionLocal2Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53, 54, 55, 57, 48, 56, 58, 59, 60, 61, 62, 63, 64]

def constructionLocal2Witnesses : List ℕ := [0, 1, 2, 3, 0, 4, 5, 6, 0, 1, 2, 3, 0, 4, 5, 7, 0, 1, 2, 3, 0, 4, 5, 6, 0, 1, 2, 3, 0, 4, 5, 8, 0, 1, 2, 3, 0, 4, 5, 6, 0, 1, 2, 3, 0, 4, 5, 0, 1, 2, 3, 0, 4, 5, 0, 7, 6, 1, 2, 3, 0, 4, 5, 8]

theorem constructionLocal2_samples_eq :
    compactCanonicalRepresentatives 2 6 constructionLocal2.rays
      constructionLocal2Centers = constructionLocal2Samples := by decide

theorem constructionLocal2_valid : constructionLocal2.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal2
    constructionLocal2Centers constructionLocal2Witnesses
  · decide
  · decide
  · change constructionLocal2.SignatureWitnessesValid
      (compactCanonicalRepresentatives 2 6 constructionLocal2.rays
        constructionLocal2Centers) constructionLocal2Witnesses
    rw [constructionLocal2_samples_eq]
    decide

end Modulus40
