import Modulus40.ConstructionLocalData.Prime47

/-!
# Local signature data at the prime 53

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal53 : LocalData where
  prime := 53
  depth := 1
  rays := [⟨53, 1, 0, 1⟩,
    ⟨53, 1, 0, 2⟩,
    ⟨53, 1, 0, 3⟩,
    ⟨53, 1, 0, 4⟩,
    ⟨53, 1, 0, 5⟩,
    ⟨53, 1, 0, 6⟩,
    ⟨53, 1, 0, 7⟩,
    ⟨53, 1, 0, 8⟩,
    ⟨53, 1, 0, 9⟩,
    ⟨53, 1, 0, 10⟩,
    ⟨53, 1, 0, 11⟩,
    ⟨53, 1, 0, 12⟩,
    ⟨53, 1, 0, 13⟩,
    ⟨53, 1, 0, 14⟩,
    ⟨53, 1, 0, 15⟩,
    ⟨53, 1, 0, 16⟩,
    ⟨53, 1, 0, 17⟩,
    ⟨53, 1, 0, 18⟩,
    ⟨53, 1, 0, 19⟩,
    ⟨53, 1, 0, 20⟩,
    ⟨53, 1, 0, 21⟩,
    ⟨53, 1, 0, 22⟩,
    ⟨53, 1, 0, 23⟩,
    ⟨53, 1, 0, 24⟩,
    ⟨53, 1, 0, 25⟩,
    ⟨53, 1, 0, 26⟩,
    ⟨53, 1, 0, 27⟩,
    ⟨53, 1, 0, 28⟩,
    ⟨53, 1, 0, 29⟩,
    ⟨53, 1, 0, 30⟩,
    ⟨53, 1, 0, 31⟩,
    ⟨53, 1, 0, 32⟩,
    ⟨53, 1, 0, 33⟩,
    ⟨53, 1, 0, 34⟩,
    ⟨53, 1, 0, 35⟩,
    ⟨53, 1, 0, 36⟩,
    ⟨53, 1, 0, 37⟩,
    ⟨53, 1, 0, 38⟩,
    ⟨53, 1, 0, 39⟩,
    ⟨53, 1, 0, 40⟩,
    ⟨53, 1, 0, 41⟩,
    ⟨53, 1, 0, 42⟩,
    ⟨53, 1, 0, 43⟩,
    ⟨53, 1, 0, 44⟩,
    ⟨53, 1, 0, 45⟩,
    ⟨53, 1, 0, 46⟩,
    ⟨53, 1, 0, 47⟩,
    ⟨53, 1, 0, 48⟩,
    ⟨53, 1, 0, 49⟩,
    ⟨53, 1, 0, 50⟩,
    ⟨53, 1, 0, 51⟩,
    ⟨53, 1, 0, 52⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12,
    .ray 1 0 13,
    .ray 1 0 14,
    .ray 1 0 15,
    .ray 1 0 16,
    .ray 1 0 17,
    .ray 1 0 18,
    .ray 1 0 19,
    .ray 1 0 20,
    .ray 1 0 21,
    .ray 1 0 22,
    .ray 1 0 23,
    .ray 1 0 24,
    .ray 1 0 25,
    .ray 1 0 26,
    .ray 1 0 27,
    .ray 1 0 28,
    .ray 1 0 29,
    .ray 1 0 30,
    .ray 1 0 31,
    .ray 1 0 32,
    .ray 1 0 33,
    .ray 1 0 34,
    .ray 1 0 35,
    .ray 1 0 36,
    .ray 1 0 37,
    .ray 1 0 38,
    .ray 1 0 39,
    .ray 1 0 40,
    .ray 1 0 41,
    .ray 1 0 42,
    .ray 1 0 43,
    .ray 1 0 44,
    .ray 1 0 45,
    .ray 1 0 46,
    .ray 1 0 47,
    .ray 1 0 48,
    .ray 1 0 49,
    .ray 1 0 50,
    .ray 1 0 51,
    .ray 1 0 52]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]

def constructionLocal53Centers : List ℤ := [0]

def constructionLocal53Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 106, 159, 212, 265, 318, 371, 424, 477, 530, 583, 636, 689, 742, 795, 848, 901, 954, 1007, 1060, 1113, 1166, 1219, 1272, 1325, 1378, 1431, 1484, 1537, 1590, 1643, 1696, 1749, 1802, 1855, 1908, 1961, 2014, 2067, 2120, 2173, 2226, 2279, 2332, 2385, 2438, 2491, 2544, 2597, 2650, 2703, 2756]

def constructionLocal53Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]

theorem constructionLocal53_samples_eq :
    compactCanonicalRepresentatives 53 1 constructionLocal53.rays
      constructionLocal53Centers = constructionLocal53Samples := by decide

theorem constructionLocal53_valid : constructionLocal53.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal53
    constructionLocal53Centers constructionLocal53Witnesses
  · decide
  · decide
  · change constructionLocal53.SignatureWitnessesValid
      (compactCanonicalRepresentatives 53 1 constructionLocal53.rays
        constructionLocal53Centers) constructionLocal53Witnesses
    rw [constructionLocal53_samples_eq]
    decide

end Modulus40
