import Modulus40.ConstructionLocalData.Prime5

/-!
# Local signature data at the prime 7

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal7 : LocalData where
  prime := 7
  depth := 2
  rays := [⟨7, 1, 0, 1⟩,
    ⟨7, 1, 0, 2⟩,
    ⟨7, 1, 0, 3⟩,
    ⟨7, 1, 0, 4⟩,
    ⟨7, 1, 0, 5⟩,
    ⟨7, 1, 0, 6⟩,
    ⟨7, 2, (-6), 1⟩,
    ⟨7, 2, (-6), 2⟩,
    ⟨7, 2, (-6), 3⟩,
    ⟨7, 2, (-6), 4⟩,
    ⟨7, 2, (-6), 5⟩,
    ⟨7, 2, (-6), 6⟩,
    ⟨7, 2, (-5), 1⟩,
    ⟨7, 2, (-5), 2⟩,
    ⟨7, 2, (-5), 3⟩,
    ⟨7, 2, (-5), 4⟩,
    ⟨7, 2, (-5), 5⟩,
    ⟨7, 2, (-5), 6⟩,
    ⟨7, 2, (-1), 1⟩,
    ⟨7, 2, (-1), 2⟩,
    ⟨7, 2, (-1), 3⟩,
    ⟨7, 2, (-1), 4⟩,
    ⟨7, 2, (-1), 5⟩,
    ⟨7, 2, (-1), 6⟩,
    ⟨7, 2, 0, 1⟩,
    ⟨7, 2, 0, 2⟩,
    ⟨7, 2, 0, 3⟩,
    ⟨7, 2, 0, 4⟩,
    ⟨7, 2, 0, 5⟩,
    ⟨7, 2, 0, 6⟩]
  coordinates := [.fixed 0 0,
    .fixed 1 0,
    .fixed 1 1,
    .fixed 1 2,
    .fixed 1 3,
    .fixed 1 4,
    .fixed 1 5,
    .fixed 1 6,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 2 (-6) 1,
    .ray 2 (-6) 2,
    .ray 2 (-6) 3,
    .ray 2 (-6) 4,
    .ray 2 (-6) 5,
    .ray 2 (-6) 6,
    .ray 2 (-5) 1,
    .ray 2 (-5) 2,
    .ray 2 (-5) 3,
    .ray 2 (-5) 4,
    .ray 2 (-5) 5,
    .ray 2 (-5) 6,
    .ray 2 (-1) 1,
    .ray 2 (-1) 2,
    .ray 2 (-1) 3,
    .ray 2 (-1) 4,
    .ray 2 (-1) 5,
    .ray 2 (-1) 6,
    .ray 2 0 1,
    .ray 2 0 2,
    .ray 2 0 3,
    .ray 2 0 4,
    .ray 2 0 5,
    .ray 2 0 6]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 14, 15, 16, 20, 21, 22, 23, 27, 28, 29, 30, 34, 35, 36, 37, 41, 42]

def constructionLocal7Centers : List ℤ := [(-6), (-5), (-1), 0]

def constructionLocal7Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 45, 46, 47, 43, 92, 141, 190, 239, 288, 44, 93, 142, 191, 240, 289, 48, 97, 146, 195, 244, 293, 49, 98, 147, 196, 245, 294]

def constructionLocal7Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 9, 10, 11, 12, 2, 3, 4, 13, 14, 15, 16, 2, 3, 4, 17, 18, 19, 20, 2, 3, 4, 21, 22, 23, 24, 2, 3, 4, 25, 26, 2, 3, 4, 0, 7, 11, 15, 19, 23, 1, 8, 12, 16, 20, 24, 5, 9, 13, 17, 21, 25, 6, 10, 14, 18, 22, 26]

theorem constructionLocal7_samples_eq :
    compactCanonicalRepresentatives 7 2 constructionLocal7.rays
      constructionLocal7Centers = constructionLocal7Samples := by decide

theorem constructionLocal7_valid : constructionLocal7.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal7
    constructionLocal7Centers constructionLocal7Witnesses
  · decide
  · decide
  · change constructionLocal7.SignatureWitnessesValid
      (compactCanonicalRepresentatives 7 2 constructionLocal7.rays
        constructionLocal7Centers) constructionLocal7Witnesses
    rw [constructionLocal7_samples_eq]
    decide

end Modulus40
