import Modulus40.ConstructionLocalData.Prime71

/-!
# Local signature data at the prime 73

Generated by `scripts/export_local_data.py` from the shared construction AST.
The chained imports bound memory use during kernel checking.
-/

namespace Modulus40

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def constructionLocal73 : LocalData where
  prime := 73
  depth := 1
  rays := [⟨73, 1, 0, 1⟩,
    ⟨73, 1, 0, 2⟩,
    ⟨73, 1, 0, 3⟩,
    ⟨73, 1, 0, 4⟩,
    ⟨73, 1, 0, 5⟩,
    ⟨73, 1, 0, 6⟩,
    ⟨73, 1, 0, 7⟩,
    ⟨73, 1, 0, 8⟩,
    ⟨73, 1, 0, 9⟩,
    ⟨73, 1, 0, 10⟩,
    ⟨73, 1, 0, 11⟩,
    ⟨73, 1, 0, 12⟩,
    ⟨73, 1, 0, 13⟩,
    ⟨73, 1, 0, 14⟩,
    ⟨73, 1, 0, 15⟩,
    ⟨73, 1, 0, 16⟩,
    ⟨73, 1, 0, 17⟩,
    ⟨73, 1, 0, 18⟩,
    ⟨73, 1, 0, 19⟩,
    ⟨73, 1, 0, 20⟩,
    ⟨73, 1, 0, 21⟩,
    ⟨73, 1, 0, 22⟩,
    ⟨73, 1, 0, 23⟩,
    ⟨73, 1, 0, 24⟩,
    ⟨73, 1, 0, 25⟩,
    ⟨73, 1, 0, 26⟩,
    ⟨73, 1, 0, 27⟩,
    ⟨73, 1, 0, 28⟩,
    ⟨73, 1, 0, 29⟩,
    ⟨73, 1, 0, 30⟩,
    ⟨73, 1, 0, 31⟩,
    ⟨73, 1, 0, 32⟩,
    ⟨73, 1, 0, 33⟩,
    ⟨73, 1, 0, 34⟩,
    ⟨73, 1, 0, 35⟩,
    ⟨73, 1, 0, 36⟩,
    ⟨73, 1, 0, 37⟩,
    ⟨73, 1, 0, 38⟩,
    ⟨73, 1, 0, 39⟩,
    ⟨73, 1, 0, 40⟩,
    ⟨73, 1, 0, 41⟩,
    ⟨73, 1, 0, 42⟩,
    ⟨73, 1, 0, 43⟩,
    ⟨73, 1, 0, 44⟩,
    ⟨73, 1, 0, 45⟩,
    ⟨73, 1, 0, 46⟩,
    ⟨73, 1, 0, 47⟩,
    ⟨73, 1, 0, 48⟩,
    ⟨73, 1, 0, 49⟩,
    ⟨73, 1, 0, 50⟩,
    ⟨73, 1, 0, 51⟩,
    ⟨73, 1, 0, 52⟩,
    ⟨73, 1, 0, 53⟩,
    ⟨73, 1, 0, 54⟩,
    ⟨73, 1, 0, 55⟩,
    ⟨73, 1, 0, 56⟩,
    ⟨73, 1, 0, 57⟩,
    ⟨73, 1, 0, 58⟩,
    ⟨73, 1, 0, 59⟩,
    ⟨73, 1, 0, 60⟩,
    ⟨73, 1, 0, 61⟩,
    ⟨73, 1, 0, 62⟩,
    ⟨73, 1, 0, 63⟩,
    ⟨73, 1, 0, 64⟩,
    ⟨73, 1, 0, 65⟩,
    ⟨73, 1, 0, 66⟩,
    ⟨73, 1, 0, 67⟩,
    ⟨73, 1, 0, 68⟩,
    ⟨73, 1, 0, 69⟩,
    ⟨73, 1, 0, 70⟩,
    ⟨73, 1, 0, 71⟩,
    ⟨73, 1, 0, 72⟩]
  coordinates := [.fixed 0 0,
    .ray 1 0 1,
    .ray 1 0 2,
    .ray 1 0 3,
    .ray 1 0 4,
    .ray 1 0 5,
    .ray 1 0 6,
    .ray 1 0 7,
    .ray 1 0 8,
    .ray 1 0 9,
    .ray 1 0 10,
    .ray 1 0 11,
    .ray 1 0 12,
    .ray 1 0 13,
    .ray 1 0 14,
    .ray 1 0 15,
    .ray 1 0 16,
    .ray 1 0 17,
    .ray 1 0 18,
    .ray 1 0 19,
    .ray 1 0 20,
    .ray 1 0 21,
    .ray 1 0 22,
    .ray 1 0 23,
    .ray 1 0 24,
    .ray 1 0 25,
    .ray 1 0 26,
    .ray 1 0 27,
    .ray 1 0 28,
    .ray 1 0 29,
    .ray 1 0 30,
    .ray 1 0 31,
    .ray 1 0 32,
    .ray 1 0 33,
    .ray 1 0 34,
    .ray 1 0 35,
    .ray 1 0 36,
    .ray 1 0 37,
    .ray 1 0 38,
    .ray 1 0 39,
    .ray 1 0 40,
    .ray 1 0 41,
    .ray 1 0 42,
    .ray 1 0 43,
    .ray 1 0 44,
    .ray 1 0 45,
    .ray 1 0 46,
    .ray 1 0 47,
    .ray 1 0 48,
    .ray 1 0 49,
    .ray 1 0 50,
    .ray 1 0 51,
    .ray 1 0 52,
    .ray 1 0 53,
    .ray 1 0 54,
    .ray 1 0 55,
    .ray 1 0 56,
    .ray 1 0 57,
    .ray 1 0 58,
    .ray 1 0 59,
    .ray 1 0 60,
    .ray 1 0 61,
    .ray 1 0 62,
    .ray 1 0 63,
    .ray 1 0 64,
    .ray 1 0 65,
    .ray 1 0 66,
    .ray 1 0 67,
    .ray 1 0 68,
    .ray 1 0 69,
    .ray 1 0 70,
    .ray 1 0 71,
    .ray 1 0 72]
  representatives := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]

def constructionLocal73Centers : List ℤ := [0]

def constructionLocal73Samples : List ℤ := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 146, 219, 292, 365, 438, 511, 584, 657, 730, 803, 876, 949, 1022, 1095, 1168, 1241, 1314, 1387, 1460, 1533, 1606, 1679, 1752, 1825, 1898, 1971, 2044, 2117, 2190, 2263, 2336, 2409, 2482, 2555, 2628, 2701, 2774, 2847, 2920, 2993, 3066, 3139, 3212, 3285, 3358, 3431, 3504, 3577, 3650, 3723, 3796, 3869, 3942, 4015, 4088, 4161, 4234, 4307, 4380, 4453, 4526, 4599, 4672, 4745, 4818, 4891, 4964, 5037, 5110, 5183, 5256]

def constructionLocal73Witnesses : List ℕ := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71]

theorem constructionLocal73_samples_eq :
    compactCanonicalRepresentatives 73 1 constructionLocal73.rays
      constructionLocal73Centers = constructionLocal73Samples := by decide

theorem constructionLocal73_valid : constructionLocal73.Valid := by
  apply LocalData.valid_of_compactWitnesses constructionLocal73
    constructionLocal73Centers constructionLocal73Witnesses
  · decide
  · decide
  · change constructionLocal73.SignatureWitnessesValid
      (compactCanonicalRepresentatives 73 1 constructionLocal73.rays
        constructionLocal73Centers) constructionLocal73Witnesses
    rw [constructionLocal73_samples_eq]
    decide

end Modulus40
