import Modulus40.SupportGateCertificateChunks.Block2

namespace Modulus40

set_option maxRecDepth 100000
set_option maxHeartbeats 0

def supportGateCertificateLookupChunk12 : Array SupportStateGateCertificate := #[
  { frames := [[], [], []], leaf := [], edgeGates := [39, 61, 972], trace := [] },
  { frames := [], leaf := [(17, 971)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 66, 134, 972], trace := [] },
  { frames := [], leaf := [(11, 393)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 394, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [40, 61, 972], trace := [] },
  { frames := [], leaf := [(17, 971)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [1008, 34, 972], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [187, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [36, 74, 972], trace := [] },
  { frames := [], leaf := [(13, 627)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 628, 972], trace := [] },
  { frames := [], leaf := [(11, 393)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [61, 394, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [39, 134, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 66, 61, 972], trace := [] },
  { frames := [], leaf := [(17, 971)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [40, 134, 972], trace := [] },
  { frames := [], leaf := [(2, 29)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [30, 972], trace := [] },
  { frames := [], leaf := [(13, 627)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [61, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 66, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 61, 134, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [39, 40, 972], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [34, 74, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [134, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 66, 628, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [1008, 61, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 34, 134, 972], trace := [] },
  { frames := [], leaf := [(11, 393)], edgeGates := [], trace := [] }
]

def supportGateCertificateLookupChunk13 : Array SupportStateGateCertificate := #[
  { frames := [[], [], []], leaf := [], edgeGates := [39, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 40, 61, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [134, 628, 972], trace := [] },
  { frames := [], leaf := [(2, 1109)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [1110, 34, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [36, 187, 972], trace := [] },
  { frames := [], leaf := [(11, 393)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [40, 394, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 74, 972], trace := [] },
  { frames := [], leaf := [(13, 627)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [39, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [66, 61, 134, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 61, 394, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [1008, 134, 972], trace := [] },
  { frames := [], leaf := [(13, 627)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [40, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [39, 34, 61, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 40, 134, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 61, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 66, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 61, 134, 972], trace := [] },
  { frames := [], leaf := [(13, 627)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [394, 628, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [34, 187, 972], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 34, 74, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 134, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 66, 628, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [1036, 61, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [39, 34, 134, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [74, 134, 972], trace := [] },
  { frames := [], leaf := [(11, 393)], edgeGates := [], trace := [] }
]

def supportGateCertificateLookupChunk14 : Array SupportStateGateCertificate := #[
  { frames := [[], [], []], leaf := [], edgeGates := [1008, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 40, 61, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 134, 628, 972], trace := [] },
  { frames := [], leaf := [(13, 627)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [66, 61, 628, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 187, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 40, 394, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [39, 74, 972], trace := [] },
  { frames := [], leaf := [(13, 627)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [1008, 628, 972], trace := [] },
  { frames := [[], [], [], [], []], leaf := [], edgeGates := [36, 66, 61, 134, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 61, 394, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [1036, 134, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [66, 134, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 40, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [1008, 34, 61, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [61, 187, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 61, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [39, 66, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [66, 134, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [39, 61, 134, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 394, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 34, 187, 972], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 34, 74, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 134, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [39, 66, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [40, 61, 134, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [30, 61, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [74, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [1008, 34, 134, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 74, 134, 972], trace := [] }
]

def supportGateCertificateLookupChunk15 : Array SupportStateGateCertificate := #[
  { frames := [[], [], []], leaf := [], edgeGates := [1036, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 134, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [61, 134, 394, 972], trace := [] },
  { frames := [[], [], [], [], []], leaf := [], edgeGates := [36, 66, 61, 628, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [39, 187, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 40, 394, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [1008, 74, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [1036, 628, 972], trace := [] },
  { frames := [[], [], [], [], []], leaf := [], edgeGates := [42, 66, 61, 134, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [66, 394, 628, 972], trace := [] },
  { frames := [], leaf := [(11, 393)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [39, 61, 394, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [30, 134, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [61, 134, 628, 972], trace := [] },
  { frames := [[], [], [], [], []], leaf := [], edgeGates := [36, 66, 134, 394, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 40, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [1110, 34, 61, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 61, 187, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [40, 61, 394, 972], trace := [] },
  { frames := [], leaf := [(13, 627)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [39, 61, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [34, 74, 134, 972], trace := [] },
  { frames := [], leaf := [(11, 393)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [1008, 34, 394, 972], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [187, 394, 972], trace := [] },
  { frames := [[], [], [], [], []], leaf := [], edgeGates := [36, 66, 134, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [1008, 61, 134, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 394, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [40, 61, 628, 972], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 34, 187, 972], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [39, 34, 74, 972], trace := [] }
]

end Modulus40
