import Modulus40.SupportGateCertificateTypes

namespace Modulus40

set_option maxRecDepth 100000
set_option maxHeartbeats 0

def supportGateCertificateLookupChunk0 : Array SupportStateGateCertificate := #[
  { frames := [], leaf := [(2, 29)], edgeGates := [], trace := [] },
  { frames := [[]], leaf := [], edgeGates := [30], trace := [] },
  { frames := [[]], leaf := [], edgeGates := [30], trace := [⟨1, 1, 30, 1, 1, 30, 1⟩] },
  { frames := [], leaf := [(2, 32)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(3, 33)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [33, 34], trace := [] },
  { frames := [], leaf := [(2, 35)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(3, 36)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [36, 37], trace := [] },
  { frames := [], leaf := [(2, 38)], edgeGates := [], trace := [] },
  { frames := [[]], leaf := [], edgeGates := [39], trace := [⟨1, 1, 39, 1, 1, 39, 1⟩] },
  { frames := [], leaf := [(3, 39)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [39, 40], trace := [] },
  { frames := [], leaf := [(2, 41)], edgeGates := [], trace := [] },
  { frames := [[]], leaf := [], edgeGates := [42], trace := [⟨1, 1, 42, 1, 1, 42, 1⟩] },
  { frames := [], leaf := [(3, 36)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [42, 37], trace := [] },
  { frames := [], leaf := [(3, 44)], edgeGates := [], trace := [] },
  { frames := [[]], leaf := [], edgeGates := [45], trace := [] },
  { frames := [[], [], [], [], [(2, 43)]], leaf := [], edgeGates := [35, 38, 41, 43, 46], trace := [⟨1, 1, 35, 1, 1, 35, 1⟩, ⟨35, 1, 38, 1, 47, 48, 47⟩, ⟨48, 47, 41, 1, 49, 51, 50⟩, ⟨51, 50, 43, 1, 52, 54, 53⟩, ⟨54, 53, 46, 1, 55, 57, 56⟩] },
  { frames := [], leaf := [(2, 38)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(5, 60)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [39, 61], trace := [] },
  { frames := [], leaf := [(2, 32)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(5, 60)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [33, 61], trace := [] },
  { frames := [], leaf := [(2, 41)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(3, 65)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(5, 60)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 66, 61], trace := [] },
  { frames := [], leaf := [(3, 39)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 40, 61], trace := [] }
]

def supportGateCertificateLookupChunk1 : Array SupportStateGateCertificate := #[
  { frames := [], leaf := [(3, 39)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [40, 61], trace := [] },
  { frames := [], leaf := [(2, 35)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [36, 40, 61], trace := [] },
  { frames := [], leaf := [(3, 33)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(5, 60)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [39, 34, 61], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [33, 34, 61], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [36, 74], trace := [] },
  { frames := [], leaf := [(2, 76)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [77, 74], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [34, 74], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [36, 34, 74], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 34, 74], trace := [] },
  { frames := [], leaf := [(2, 83)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [84, 34, 74], trace := [] },
  { frames := [], leaf := [(5, 86)], edgeGates := [], trace := [] },
  { frames := [[]], leaf := [], edgeGates := [87], trace := [] },
  { frames := [[(3, 2)], [(3, 2)], [], [], [(2, 43)], [], [], [], [(3, 2)], [(3, 2)], [(2, 43)], [], [], [], [(2, 43), (3, 2)]], leaf := [], edgeGates := [63, 65, 67, 68, 70, 71, 72, 73, 76, 79, 81, 82, 83, 85, 88], trace := [⟨1, 1, 63, 1, 1, 63, 1⟩, ⟨63, 1, 65, 1, 89, 90, 89⟩, ⟨90, 89, 67, 1, 91, 93, 92⟩, ⟨93, 92, 68, 1, 94, 96, 95⟩, ⟨96, 95, 70, 1, 97, 99, 98⟩, ⟨99, 98, 71, 1, 100, 102, 101⟩, ⟨102, 101, 72, 1, 103, 105, 104⟩, ⟨105, 104, 73, 1, 106, 108, 107⟩, ⟨108, 107, 76, 1, 109, 111, 110⟩, ⟨111, 110, 79, 1, 112, 114, 113⟩, ⟨114, 113, 81, 1, 115, 117, 116⟩, ⟨117, 116, 82, 1, 118, 120, 119⟩, ⟨120, 119, 83, 1, 121, 123, 122⟩, ⟨123, 122, 85, 1, 124, 126, 125⟩, ⟨126, 125, 88, 1, 127, 129, 128⟩] },
  { frames := [], leaf := [(2, 83)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(7, 133)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [84, 134], trace := [] },
  { frames := [], leaf := [(7, 133)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [36, 66, 134], trace := [] },
  { frames := [], leaf := [(2, 41)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(3, 65)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 66, 134], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [40, 134], trace := [] }
]

def supportGateCertificateLookupChunk2 : Array SupportStateGateCertificate := #[
  { frames := [[], [], []], leaf := [], edgeGates := [36, 40, 134], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [], leaf := [(7, 133)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [74, 134], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [36, 74, 134], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 74, 134], trace := [] },
  { frames := [], leaf := [(5, 73)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [84, 74, 134], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [36, 61, 134], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [66, 61, 134], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 66, 61, 134], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 61, 134], trace := [] },
  { frames := [], leaf := [(5, 160)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [34, 161, 134], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 34, 161, 134], trace := [] },
  { frames := [], leaf := [(7, 133)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [84, 66, 134], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 40, 134], trace := [] },
  { frames := [], leaf := [(3, 39)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [84, 40, 134], trace := [] },
  { frames := [], leaf := [(3, 65)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 66, 61, 134], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [40, 61, 134], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 40, 61, 134], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 40, 61, 134], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [84, 40, 61, 134], trace := [] },
  { frames := [], leaf := [(5, 86)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [66, 87, 134], trace := [] },
  { frames := [], leaf := [(5, 86)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 66, 87, 134], trace := [] }
]

def supportGateCertificateLookupChunk3 : Array SupportStateGateCertificate := #[
  { frames := [], leaf := [(5, 86)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 66, 87, 134], trace := [] },
  { frames := [], leaf := [(5, 86)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [84, 66, 87, 134], trace := [] },
  { frames := [], leaf := [(7, 133)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [84, 61, 134], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [84, 66, 61, 134], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 34, 161, 134], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [84, 34, 161, 134], trace := [] },
  { frames := [], leaf := [(7, 186)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [36, 161, 187], trace := [] },
  { frames := [], leaf := [(7, 186)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 161, 187], trace := [] },
  { frames := [], leaf := [(7, 186)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [34, 161, 187], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 34, 161, 187], trace := [] },
  { frames := [], leaf := [(7, 186)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [161, 187], trace := [] },
  { frames := [], leaf := [(7, 186)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [84, 161, 187], trace := [] },
  { frames := [], leaf := [(7, 186)], edgeGates := [], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [42, 34, 161, 187], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [84, 34, 161, 187], trace := [] },
  { frames := [], leaf := [(7, 186)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [36, 61, 187], trace := [] },
  { frames := [], leaf := [(7, 186)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [42, 61, 187], trace := [] },
  { frames := [], leaf := [(7, 186)], edgeGates := [], trace := [] },
  { frames := [[], [], []], leaf := [], edgeGates := [34, 61, 187], trace := [] },
  { frames := [[], [], [], []], leaf := [], edgeGates := [36, 34, 61, 187], trace := [] },
  { frames := [], leaf := [(7, 186)], edgeGates := [], trace := [] },
  { frames := [[], []], leaf := [], edgeGates := [61, 187], trace := [] }
]

end Modulus40
