import Modulus40.ConstructionLocalData.Prime103

/-!
# Validated local signatures for all construction primes

Generated by `scripts/export_local_data.py`; every local table has a kernel-checked validity proof.
-/

namespace Modulus40

def constructionLocals : Fin 27 → LocalData := ![constructionLocal2, constructionLocal3, constructionLocal5, constructionLocal7, constructionLocal11, constructionLocal13, constructionLocal17, constructionLocal19, constructionLocal23, constructionLocal29, constructionLocal31, constructionLocal37, constructionLocal41, constructionLocal43, constructionLocal47, constructionLocal53, constructionLocal59, constructionLocal61, constructionLocal67, constructionLocal71, constructionLocal73, constructionLocal79, constructionLocal83, constructionLocal89, constructionLocal97, constructionLocal101, constructionLocal103]

theorem constructionLocals_valid : ∀ i, (constructionLocals i).Valid := by
  intro i
  fin_cases i
  · exact constructionLocal2_valid
  · exact constructionLocal3_valid
  · exact constructionLocal5_valid
  · exact constructionLocal7_valid
  · exact constructionLocal11_valid
  · exact constructionLocal13_valid
  · exact constructionLocal17_valid
  · exact constructionLocal19_valid
  · exact constructionLocal23_valid
  · exact constructionLocal29_valid
  · exact constructionLocal31_valid
  · exact constructionLocal37_valid
  · exact constructionLocal41_valid
  · exact constructionLocal43_valid
  · exact constructionLocal47_valid
  · exact constructionLocal53_valid
  · exact constructionLocal59_valid
  · exact constructionLocal61_valid
  · exact constructionLocal67_valid
  · exact constructionLocal71_valid
  · exact constructionLocal73_valid
  · exact constructionLocal79_valid
  · exact constructionLocal83_valid
  · exact constructionLocal89_valid
  · exact constructionLocal97_valid
  · exact constructionLocal101_valid
  · exact constructionLocal103_valid

end Modulus40
