import Modulus40.Compile
import Modulus40.IndexedCore

/-!
# Explicit data for sections 4.1–4.4

Generated by `scripts/generate_initial_lean.py` from the transcribed paper.
This is a partial certificate, with holes subsequently filled in the paper.
-/

namespace Modulus40

set_option maxRecDepth 100000
set_option maxHeartbeats 0

def initialPrimes : Fin 4 → ℕ := ![2, 3, 5, 7]

def initialPatterns : Certificate := [
  -- 0: section 4.1
  [.ray ⟨2, 6, 0, 1⟩],
  -- 1: section 4.2
  [.ray ⟨2, 4, -1, 1⟩, .ray ⟨3, 1, 0, 2⟩],
  -- 2: section 4.2
  [.fixed ⟨2, 1⟩, .ray ⟨3, 3, 0, 1⟩],
  -- 3: section 4.2
  [.fixed ⟨8, 3⟩, .ray ⟨3, 2, 0, 2⟩],
  -- 4: section 4.2
  [.fixed ⟨4, 1⟩, .ray ⟨3, 3, 0, 2⟩],
  -- 5: section 4.2 extra 81
  [.ray ⟨3, 4, -6, 1⟩],
  -- 6: section 4.3
  [.fixed ⟨8, 4⟩, .fixed ⟨5, 1⟩],
  -- 7: section 4.3
  [.ray ⟨2, 4, -4, 1⟩, .fixed ⟨5, 2⟩],
  -- 8: section 4.3
  [.fixed ⟨4, 0⟩, .fixed ⟨3, 1⟩, .fixed ⟨5, 3⟩],
  -- 9: section 4.3
  [.fixed ⟨4, 0⟩, .ray ⟨3, 2, -1, 1⟩, .fixed ⟨5, 3⟩],
  -- 10: section 4.3
  [.ray ⟨3, 2, 0, 1⟩, .fixed ⟨5, 3⟩],
  -- 11: section 4.3
  [.fixed ⟨2, 0⟩, .ray ⟨3, 2, 0, 2⟩, .fixed ⟨5, 3⟩],
  -- 12: section 4.3
  [.fixed ⟨8, 4⟩, .ray ⟨3, 1, 0, 1⟩, .fixed ⟨5, 4⟩],
  -- 13: section 4.3
  [.ray ⟨2, 4, -4, 1⟩, .ray ⟨3, 1, 0, 2⟩, .fixed ⟨5, 4⟩],
  -- 14: section 4.3
  [.fixed ⟨2, 0⟩, .ray ⟨5, 2, 0, 1⟩],
  -- 15: section 4.3
  [.ray ⟨2, 2, 0, 1⟩, .ray ⟨5, 2, 0, 2⟩],
  -- 16: section 4.3
  [.ray ⟨3, 1, 0, 1⟩, .ray ⟨5, 2, 0, 3⟩],
  -- 17: section 4.3
  [.fixed ⟨2, 0⟩, .ray ⟨3, 1, 0, 2⟩, .ray ⟨5, 2, 0, 3⟩],
  -- 18: section 4.3
  [.fixed ⟨4, 0⟩, .ray ⟨3, 1, 0, 1⟩, .ray ⟨5, 2, 0, 4⟩],
  -- 19: section 4.3
  [.ray ⟨2, 3, 0, 1⟩, .ray ⟨3, 1, 0, 2⟩, .ray ⟨5, 2, 0, 4⟩],
  -- 20: section 4.3 extra 125
  [.ray ⟨5, 3, 0, 4⟩],
  -- 21: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .fixed ⟨7, 2⟩],
  -- 22: section 4.4
  [.fixed ⟨2, 0⟩, .fixed ⟨3, 1⟩, .fixed ⟨7, 3⟩],
  -- 23: section 4.4
  [.fixed ⟨4, 2⟩, .fixed ⟨3, 2⟩, .fixed ⟨7, 3⟩],
  -- 24: section 4.4
  [.ray ⟨3, 2, 0, 1⟩, .fixed ⟨7, 3⟩],
  -- 25: section 4.4
  [.fixed ⟨2, 0⟩, .ray ⟨3, 2, 0, 2⟩, .fixed ⟨7, 3⟩],
  -- 26: section 4.4
  [.ray ⟨5, 2, -4, 1⟩, .fixed ⟨7, 4⟩],
  -- 27: section 4.4
  [.fixed ⟨2, 0⟩, .ray ⟨5, 2, -4, 2⟩, .fixed ⟨7, 4⟩],
  -- 28: section 4.4
  [.fixed ⟨4, 2⟩, .ray ⟨5, 2, -4, 3⟩, .fixed ⟨7, 4⟩],
  -- 29: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .ray ⟨5, 2, -4, 4⟩, .fixed ⟨7, 4⟩],
  -- 30: section 4.4
  [.fixed ⟨2, 0⟩, .fixed ⟨5, 2⟩, .fixed ⟨7, 4⟩],
  -- 31: section 4.4
  [.fixed ⟨3, 1⟩, .fixed ⟨5, 3⟩, .fixed ⟨7, 4⟩],
  -- 32: section 4.4
  [.fixed ⟨2, 0⟩, .fixed ⟨3, 2⟩, .fixed ⟨5, 3⟩, .fixed ⟨7, 4⟩],
  -- 33: section 4.4
  [.fixed ⟨4, 2⟩, .fixed ⟨5, 4⟩, .fixed ⟨7, 4⟩],
  -- 34: section 4.4
  [.ray ⟨3, 1, 0, 1⟩, .fixed ⟨25, 20⟩, .fixed ⟨7, 4⟩],
  -- 35: section 4.4
  [.fixed ⟨2, 0⟩, .ray ⟨3, 1, 0, 2⟩, .fixed ⟨25, 20⟩, .fixed ⟨7, 4⟩],
  -- 36: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .fixed ⟨3, 1⟩, .fixed ⟨7, 5⟩],
  -- 37: section 4.4
  [.fixed ⟨4, 2⟩, .ray ⟨3, 2, -1, 1⟩, .fixed ⟨7, 5⟩],
  -- 38: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .ray ⟨3, 2, -1, 2⟩, .fixed ⟨7, 5⟩],
  -- 39: section 4.4
  [.fixed ⟨4, 2⟩, .fixed ⟨3, 0⟩, .fixed ⟨5, 1⟩, .fixed ⟨7, 5⟩],
  -- 40: section 4.4
  [.ray ⟨3, 2, 0, 1⟩, .fixed ⟨5, 2⟩, .fixed ⟨7, 5⟩],
  -- 41: section 4.4
  [.fixed ⟨2, 0⟩, .ray ⟨3, 2, 0, 2⟩, .fixed ⟨5, 2⟩, .fixed ⟨7, 5⟩],
  -- 42: section 4.4
  [.fixed ⟨4, 2⟩, .ray ⟨3, 2, 0, 1⟩, .fixed ⟨5, 4⟩, .fixed ⟨7, 5⟩],
  -- 43: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .ray ⟨3, 2, 0, 2⟩, .fixed ⟨5, 4⟩, .fixed ⟨7, 5⟩],
  -- 44: section 4.4
  [.fixed ⟨3, 0⟩, .ray ⟨5, 3, -5, 1⟩, .fixed ⟨7, 5⟩],
  -- 45: section 4.4
  [.fixed ⟨2, 0⟩, .fixed ⟨3, 0⟩, .ray ⟨5, 3, -5, 2⟩, .fixed ⟨7, 5⟩],
  -- 46: section 4.4
  [.fixed ⟨4, 2⟩, .fixed ⟨3, 0⟩, .ray ⟨5, 3, -5, 3⟩, .fixed ⟨7, 5⟩],
  -- 47: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .fixed ⟨3, 0⟩, .ray ⟨5, 3, -5, 4⟩, .fixed ⟨7, 5⟩],
  -- 48: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .fixed ⟨5, 1⟩, .fixed ⟨7, 6⟩],
  -- 49: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .fixed ⟨3, 1⟩, .fixed ⟨5, 3⟩, .fixed ⟨7, 6⟩],
  -- 50: section 4.4
  [.fixed ⟨4, 2⟩, .ray ⟨3, 1, 0, 1⟩, .fixed ⟨25, 20⟩, .fixed ⟨7, 6⟩],
  -- 51: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .ray ⟨3, 1, 0, 2⟩, .fixed ⟨25, 20⟩, .fixed ⟨7, 6⟩],
  -- 52: section 4.4
  [.fixed ⟨2, 0⟩, .fixed ⟨25, 20⟩, .ray ⟨7, 2, -6, 1⟩],
  -- 53: section 4.4
  [.fixed ⟨4, 2⟩, .fixed ⟨25, 20⟩, .ray ⟨7, 2, -6, 2⟩],
  -- 54: section 4.4
  [.ray ⟨3, 1, 0, 1⟩, .fixed ⟨25, 20⟩, .ray ⟨7, 2, -6, 3⟩],
  -- 55: section 4.4
  [.fixed ⟨2, 0⟩, .ray ⟨3, 1, 0, 2⟩, .fixed ⟨25, 20⟩, .ray ⟨7, 2, -6, 3⟩],
  -- 56: section 4.4
  [.fixed ⟨25, 20⟩, .ray ⟨7, 2, -6, 4⟩],
  -- 57: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .fixed ⟨25, 20⟩, .ray ⟨7, 2, -6, 5⟩],
  -- 58: section 4.4
  [.fixed ⟨4, 2⟩, .ray ⟨3, 1, 0, 1⟩, .fixed ⟨25, 20⟩, .ray ⟨7, 2, -6, 6⟩],
  -- 59: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .ray ⟨3, 1, 0, 2⟩, .fixed ⟨25, 20⟩, .ray ⟨7, 2, -6, 6⟩],
  -- 60: section 4.4
  [.fixed ⟨2, 0⟩, .fixed ⟨5, 4⟩, .ray ⟨7, 2, -1, 1⟩],
  -- 61: section 4.4
  [.fixed ⟨4, 2⟩, .fixed ⟨5, 4⟩, .ray ⟨7, 2, -1, 2⟩],
  -- 62: section 4.4
  [.ray ⟨3, 1, 0, 1⟩, .fixed ⟨5, 4⟩, .ray ⟨7, 2, -1, 3⟩],
  -- 63: section 4.4
  [.fixed ⟨2, 0⟩, .ray ⟨3, 1, 0, 2⟩, .fixed ⟨5, 4⟩, .ray ⟨7, 2, -1, 3⟩],
  -- 64: section 4.4
  [.fixed ⟨5, 4⟩, .ray ⟨7, 2, -1, 4⟩],
  -- 65: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .fixed ⟨5, 4⟩, .ray ⟨7, 2, -1, 5⟩],
  -- 66: section 4.4
  [.fixed ⟨4, 2⟩, .ray ⟨3, 1, 0, 1⟩, .fixed ⟨5, 4⟩, .ray ⟨7, 2, -1, 6⟩],
  -- 67: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .ray ⟨3, 1, 0, 2⟩, .fixed ⟨5, 4⟩, .ray ⟨7, 2, -1, 6⟩],
  -- 68: section 4.4
  [.fixed ⟨2, 0⟩, .ray ⟨7, 2, 0, 1⟩],
  -- 69: section 4.4
  [.fixed ⟨4, 2⟩, .ray ⟨7, 2, 0, 2⟩],
  -- 70: section 4.4
  [.ray ⟨3, 1, 0, 1⟩, .ray ⟨7, 2, 0, 3⟩],
  -- 71: section 4.4
  [.fixed ⟨2, 0⟩, .ray ⟨3, 1, 0, 2⟩, .ray ⟨7, 2, 0, 3⟩],
  -- 72: section 4.4
  [.ray ⟨7, 2, 0, 4⟩],
  -- 73: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .ray ⟨7, 2, 0, 5⟩],
  -- 74: section 4.4
  [.fixed ⟨4, 2⟩, .ray ⟨3, 1, 0, 1⟩, .ray ⟨7, 2, 0, 6⟩],
  -- 75: section 4.4
  [.ray ⟨2, 3, -2, 1⟩, .ray ⟨3, 1, 0, 2⟩, .ray ⟨7, 2, 0, 6⟩]
]

def initialBoxes : Fin 76 → SupportBox 4 := ![
  ![.ray 6, .fixed 0, .fixed 0, .fixed 0],
  ![.ray 4, .ray 1, .fixed 0, .fixed 0],
  ![.fixed 1, .ray 3, .fixed 0, .fixed 0],
  ![.fixed 3, .ray 2, .fixed 0, .fixed 0],
  ![.fixed 2, .ray 3, .fixed 0, .fixed 0],
  ![.fixed 0, .ray 4, .fixed 0, .fixed 0],
  ![.fixed 3, .fixed 0, .fixed 1, .fixed 0],
  ![.ray 4, .fixed 0, .fixed 1, .fixed 0],
  ![.fixed 2, .fixed 1, .fixed 1, .fixed 0],
  ![.fixed 2, .ray 2, .fixed 1, .fixed 0],
  ![.fixed 0, .ray 2, .fixed 1, .fixed 0],
  ![.fixed 1, .ray 2, .fixed 1, .fixed 0],
  ![.fixed 3, .ray 1, .fixed 1, .fixed 0],
  ![.ray 4, .ray 1, .fixed 1, .fixed 0],
  ![.fixed 1, .fixed 0, .ray 2, .fixed 0],
  ![.ray 2, .fixed 0, .ray 2, .fixed 0],
  ![.fixed 0, .ray 1, .ray 2, .fixed 0],
  ![.fixed 1, .ray 1, .ray 2, .fixed 0],
  ![.fixed 2, .ray 1, .ray 2, .fixed 0],
  ![.ray 3, .ray 1, .ray 2, .fixed 0],
  ![.fixed 0, .fixed 0, .ray 3, .fixed 0],
  ![.ray 3, .fixed 0, .fixed 0, .fixed 1],
  ![.fixed 1, .fixed 1, .fixed 0, .fixed 1],
  ![.fixed 2, .fixed 1, .fixed 0, .fixed 1],
  ![.fixed 0, .ray 2, .fixed 0, .fixed 1],
  ![.fixed 1, .ray 2, .fixed 0, .fixed 1],
  ![.fixed 0, .fixed 0, .ray 2, .fixed 1],
  ![.fixed 1, .fixed 0, .ray 2, .fixed 1],
  ![.fixed 2, .fixed 0, .ray 2, .fixed 1],
  ![.ray 3, .fixed 0, .ray 2, .fixed 1],
  ![.fixed 1, .fixed 0, .fixed 1, .fixed 1],
  ![.fixed 0, .fixed 1, .fixed 1, .fixed 1],
  ![.fixed 1, .fixed 1, .fixed 1, .fixed 1],
  ![.fixed 2, .fixed 0, .fixed 1, .fixed 1],
  ![.fixed 0, .ray 1, .fixed 2, .fixed 1],
  ![.fixed 1, .ray 1, .fixed 2, .fixed 1],
  ![.ray 3, .fixed 1, .fixed 0, .fixed 1],
  ![.fixed 2, .ray 2, .fixed 0, .fixed 1],
  ![.ray 3, .ray 2, .fixed 0, .fixed 1],
  ![.fixed 2, .fixed 1, .fixed 1, .fixed 1],
  ![.fixed 0, .ray 2, .fixed 1, .fixed 1],
  ![.fixed 1, .ray 2, .fixed 1, .fixed 1],
  ![.fixed 2, .ray 2, .fixed 1, .fixed 1],
  ![.ray 3, .ray 2, .fixed 1, .fixed 1],
  ![.fixed 0, .fixed 1, .ray 3, .fixed 1],
  ![.fixed 1, .fixed 1, .ray 3, .fixed 1],
  ![.fixed 2, .fixed 1, .ray 3, .fixed 1],
  ![.ray 3, .fixed 1, .ray 3, .fixed 1],
  ![.ray 3, .fixed 0, .fixed 1, .fixed 1],
  ![.ray 3, .fixed 1, .fixed 1, .fixed 1],
  ![.fixed 2, .ray 1, .fixed 2, .fixed 1],
  ![.ray 3, .ray 1, .fixed 2, .fixed 1],
  ![.fixed 1, .fixed 0, .fixed 2, .ray 2],
  ![.fixed 2, .fixed 0, .fixed 2, .ray 2],
  ![.fixed 0, .ray 1, .fixed 2, .ray 2],
  ![.fixed 1, .ray 1, .fixed 2, .ray 2],
  ![.fixed 0, .fixed 0, .fixed 2, .ray 2],
  ![.ray 3, .fixed 0, .fixed 2, .ray 2],
  ![.fixed 2, .ray 1, .fixed 2, .ray 2],
  ![.ray 3, .ray 1, .fixed 2, .ray 2],
  ![.fixed 1, .fixed 0, .fixed 1, .ray 2],
  ![.fixed 2, .fixed 0, .fixed 1, .ray 2],
  ![.fixed 0, .ray 1, .fixed 1, .ray 2],
  ![.fixed 1, .ray 1, .fixed 1, .ray 2],
  ![.fixed 0, .fixed 0, .fixed 1, .ray 2],
  ![.ray 3, .fixed 0, .fixed 1, .ray 2],
  ![.fixed 2, .ray 1, .fixed 1, .ray 2],
  ![.ray 3, .ray 1, .fixed 1, .ray 2],
  ![.fixed 1, .fixed 0, .fixed 0, .ray 2],
  ![.fixed 2, .fixed 0, .fixed 0, .ray 2],
  ![.fixed 0, .ray 1, .fixed 0, .ray 2],
  ![.fixed 1, .ray 1, .fixed 0, .ray 2],
  ![.fixed 0, .fixed 0, .fixed 0, .ray 2],
  ![.ray 3, .fixed 0, .fixed 0, .ray 2],
  ![.fixed 2, .ray 1, .fixed 0, .ray 2],
  ![.ray 3, .ray 1, .fixed 0, .ray 2]
]

def initialPrimePatterns : Fin 76 → PrimePattern 4 := ![
  ![.ray 6 (0) 1, .fixed 0 0, .fixed 0 0, .fixed 0 0],
  ![.ray 4 (-1) 1, .ray 1 (0) 2, .fixed 0 0, .fixed 0 0],
  ![.fixed 1 (1), .ray 3 (0) 1, .fixed 0 0, .fixed 0 0],
  ![.fixed 3 (3), .ray 2 (0) 2, .fixed 0 0, .fixed 0 0],
  ![.fixed 2 (1), .ray 3 (0) 2, .fixed 0 0, .fixed 0 0],
  ![.fixed 0 0, .ray 4 (-6) 1, .fixed 0 0, .fixed 0 0],
  ![.fixed 3 (4), .fixed 0 0, .fixed 1 (1), .fixed 0 0],
  ![.ray 4 (-4) 1, .fixed 0 0, .fixed 1 (2), .fixed 0 0],
  ![.fixed 2 (0), .fixed 1 (1), .fixed 1 (3), .fixed 0 0],
  ![.fixed 2 (0), .ray 2 (-1) 1, .fixed 1 (3), .fixed 0 0],
  ![.fixed 0 0, .ray 2 (0) 1, .fixed 1 (3), .fixed 0 0],
  ![.fixed 1 (0), .ray 2 (0) 2, .fixed 1 (3), .fixed 0 0],
  ![.fixed 3 (4), .ray 1 (0) 1, .fixed 1 (4), .fixed 0 0],
  ![.ray 4 (-4) 1, .ray 1 (0) 2, .fixed 1 (4), .fixed 0 0],
  ![.fixed 1 (0), .fixed 0 0, .ray 2 (0) 1, .fixed 0 0],
  ![.ray 2 (0) 1, .fixed 0 0, .ray 2 (0) 2, .fixed 0 0],
  ![.fixed 0 0, .ray 1 (0) 1, .ray 2 (0) 3, .fixed 0 0],
  ![.fixed 1 (0), .ray 1 (0) 2, .ray 2 (0) 3, .fixed 0 0],
  ![.fixed 2 (0), .ray 1 (0) 1, .ray 2 (0) 4, .fixed 0 0],
  ![.ray 3 (0) 1, .ray 1 (0) 2, .ray 2 (0) 4, .fixed 0 0],
  ![.fixed 0 0, .fixed 0 0, .ray 3 (0) 4, .fixed 0 0],
  ![.ray 3 (-2) 1, .fixed 0 0, .fixed 0 0, .fixed 1 (2)],
  ![.fixed 1 (0), .fixed 1 (1), .fixed 0 0, .fixed 1 (3)],
  ![.fixed 2 (2), .fixed 1 (2), .fixed 0 0, .fixed 1 (3)],
  ![.fixed 0 0, .ray 2 (0) 1, .fixed 0 0, .fixed 1 (3)],
  ![.fixed 1 (0), .ray 2 (0) 2, .fixed 0 0, .fixed 1 (3)],
  ![.fixed 0 0, .fixed 0 0, .ray 2 (-4) 1, .fixed 1 (4)],
  ![.fixed 1 (0), .fixed 0 0, .ray 2 (-4) 2, .fixed 1 (4)],
  ![.fixed 2 (2), .fixed 0 0, .ray 2 (-4) 3, .fixed 1 (4)],
  ![.ray 3 (-2) 1, .fixed 0 0, .ray 2 (-4) 4, .fixed 1 (4)],
  ![.fixed 1 (0), .fixed 0 0, .fixed 1 (2), .fixed 1 (4)],
  ![.fixed 0 0, .fixed 1 (1), .fixed 1 (3), .fixed 1 (4)],
  ![.fixed 1 (0), .fixed 1 (2), .fixed 1 (3), .fixed 1 (4)],
  ![.fixed 2 (2), .fixed 0 0, .fixed 1 (4), .fixed 1 (4)],
  ![.fixed 0 0, .ray 1 (0) 1, .fixed 2 (20), .fixed 1 (4)],
  ![.fixed 1 (0), .ray 1 (0) 2, .fixed 2 (20), .fixed 1 (4)],
  ![.ray 3 (-2) 1, .fixed 1 (1), .fixed 0 0, .fixed 1 (5)],
  ![.fixed 2 (2), .ray 2 (-1) 1, .fixed 0 0, .fixed 1 (5)],
  ![.ray 3 (-2) 1, .ray 2 (-1) 2, .fixed 0 0, .fixed 1 (5)],
  ![.fixed 2 (2), .fixed 1 (0), .fixed 1 (1), .fixed 1 (5)],
  ![.fixed 0 0, .ray 2 (0) 1, .fixed 1 (2), .fixed 1 (5)],
  ![.fixed 1 (0), .ray 2 (0) 2, .fixed 1 (2), .fixed 1 (5)],
  ![.fixed 2 (2), .ray 2 (0) 1, .fixed 1 (4), .fixed 1 (5)],
  ![.ray 3 (-2) 1, .ray 2 (0) 2, .fixed 1 (4), .fixed 1 (5)],
  ![.fixed 0 0, .fixed 1 (0), .ray 3 (-5) 1, .fixed 1 (5)],
  ![.fixed 1 (0), .fixed 1 (0), .ray 3 (-5) 2, .fixed 1 (5)],
  ![.fixed 2 (2), .fixed 1 (0), .ray 3 (-5) 3, .fixed 1 (5)],
  ![.ray 3 (-2) 1, .fixed 1 (0), .ray 3 (-5) 4, .fixed 1 (5)],
  ![.ray 3 (-2) 1, .fixed 0 0, .fixed 1 (1), .fixed 1 (6)],
  ![.ray 3 (-2) 1, .fixed 1 (1), .fixed 1 (3), .fixed 1 (6)],
  ![.fixed 2 (2), .ray 1 (0) 1, .fixed 2 (20), .fixed 1 (6)],
  ![.ray 3 (-2) 1, .ray 1 (0) 2, .fixed 2 (20), .fixed 1 (6)],
  ![.fixed 1 (0), .fixed 0 0, .fixed 2 (20), .ray 2 (-6) 1],
  ![.fixed 2 (2), .fixed 0 0, .fixed 2 (20), .ray 2 (-6) 2],
  ![.fixed 0 0, .ray 1 (0) 1, .fixed 2 (20), .ray 2 (-6) 3],
  ![.fixed 1 (0), .ray 1 (0) 2, .fixed 2 (20), .ray 2 (-6) 3],
  ![.fixed 0 0, .fixed 0 0, .fixed 2 (20), .ray 2 (-6) 4],
  ![.ray 3 (-2) 1, .fixed 0 0, .fixed 2 (20), .ray 2 (-6) 5],
  ![.fixed 2 (2), .ray 1 (0) 1, .fixed 2 (20), .ray 2 (-6) 6],
  ![.ray 3 (-2) 1, .ray 1 (0) 2, .fixed 2 (20), .ray 2 (-6) 6],
  ![.fixed 1 (0), .fixed 0 0, .fixed 1 (4), .ray 2 (-1) 1],
  ![.fixed 2 (2), .fixed 0 0, .fixed 1 (4), .ray 2 (-1) 2],
  ![.fixed 0 0, .ray 1 (0) 1, .fixed 1 (4), .ray 2 (-1) 3],
  ![.fixed 1 (0), .ray 1 (0) 2, .fixed 1 (4), .ray 2 (-1) 3],
  ![.fixed 0 0, .fixed 0 0, .fixed 1 (4), .ray 2 (-1) 4],
  ![.ray 3 (-2) 1, .fixed 0 0, .fixed 1 (4), .ray 2 (-1) 5],
  ![.fixed 2 (2), .ray 1 (0) 1, .fixed 1 (4), .ray 2 (-1) 6],
  ![.ray 3 (-2) 1, .ray 1 (0) 2, .fixed 1 (4), .ray 2 (-1) 6],
  ![.fixed 1 (0), .fixed 0 0, .fixed 0 0, .ray 2 (0) 1],
  ![.fixed 2 (2), .fixed 0 0, .fixed 0 0, .ray 2 (0) 2],
  ![.fixed 0 0, .ray 1 (0) 1, .fixed 0 0, .ray 2 (0) 3],
  ![.fixed 1 (0), .ray 1 (0) 2, .fixed 0 0, .ray 2 (0) 3],
  ![.fixed 0 0, .fixed 0 0, .fixed 0 0, .ray 2 (0) 4],
  ![.ray 3 (-2) 1, .fixed 0 0, .fixed 0 0, .ray 2 (0) 5],
  ![.fixed 2 (2), .ray 1 (0) 1, .fixed 0 0, .ray 2 (0) 6],
  ![.ray 3 (-2) 1, .ray 1 (0) 2, .fixed 0 0, .ray 2 (0) 6]
]

theorem initialPatterns_valid : ∀ ss ∈ initialPatterns, ss.Valid := by
  decide

theorem initialPrimes_prime : ∀ i, (initialPrimes i).Prime := by decide

theorem initialPrimes_injective : Function.Injective initialPrimes := by decide

theorem initialBoxes_match : ∀ i j,
    initialBoxes i j = primePatternBoxes initialPrimePatterns i j := by decide

theorem initialBoxes_separated : ∀ i j, i ≠ j →
    (primePatternBoxes initialPrimePatterns i).Separated
      (primePatternBoxes initialPrimePatterns j) := by decide

theorem initialBoxes_minimum : ∀ i, 40 ≤ supportModulus initialPrimes
    (fun j => (initialPrimePatterns i j).interval.lo) := by decide

/-- Actual ordinary classes in the first four sections have no repeated modulus,
at every finite truncation depth. This does not assert they cover all integers. -/
theorem initialCore_distinct (bound : ℕ) :
    DistinctModuli (indexedCore initialPrimes initialPrimes_prime
      initialPrimes_injective initialPrimePatterns bound) :=
  indexedCore_distinct initialPrimes initialPrimes_prime initialPrimes_injective
    initialPrimePatterns initialBoxes_separated

/-- The modulus 40 occurs as 4 (mod 8) intersected with 1 (mod 5). -/
theorem initialCore_minimum (bound : ℕ) (hbound : 3 ≤ bound) :
    HasSmallestModulus (indexedCore initialPrimes initialPrimes_prime
      initialPrimes_injective initialPrimePatterns bound) 40 := by
  constructor
  · intro c hc
    exact indexedCore_modulus_lower_bound initialPrimes initialPrimes_prime
      initialPrimes_injective initialPrimePatterns initialBoxes_minimum hc
  · apply indexedCore_attains initialPrimes initialPrimes_prime initialPrimes_injective
      initialPrimePatterns ⟨6, by decide⟩ ![3, 0, 1, 0]
    · decide
    · intro j; fin_cases j <;> simp <;> omega
    · decide

end Modulus40
