#!/usr/bin/env python3
"""Reproduce the concrete Lean counterexamples for the Owens transcription.

This producer is untrusted. Lean computes rejection of every explicit family
and proves that the arithmetic tests imply non-membership in the infinite rays.
It does not prove that every possible construction with minimum 42 fails.
"""
from __future__ import annotations

import argparse
import owens42 as o


def integer(value: int) -> str:
    return str(value) if value >= 0 else f"({value})"


def family_text(family) -> str:
    entries = []
    for pc in family.selectors:
        if pc.kind == "fixed":
            coordinate = f".fixed {pc.lo} {integer(pc.residue)}"
        elif pc.hi is not None:
            assert pc.hi == pc.lo
            residue = pc.center + pc.digit * pc.p ** (pc.lo - 1)
            coordinate = f".fixed {pc.lo} {integer(residue)}"
        else:
            assert pc.kind == "ray" and pc.hi is None
            coordinate = f".ray {pc.lo} {integer(pc.center)} {pc.digit}"
        entries.append(f"({pc.p}, {coordinate})")
    return "  [" + ", ".join(entries) + "]"


def render(expressions, count, stem, witness, description):
    families = [f for _, e in expressions[:count] for f in o.s.compile_expr(e)]
    assert all(not f.matches({pc.p: witness for pc in f.selectors}) for f in families)
    assert all(pc.kind != "ray" or pc.center != witness
               for f in families for pc in f.selectors)
    rows = ",\n".join(map(family_text, families))
    return f'''import Modulus42.ArithmeticChecks

/-! Generated by scripts/export_owens42_gaps.py. This is a counterexample
to coverage of an explicit prefix, not a disproof of MinimumModulus42. -/
namespace Modulus42
open Modulus40
set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-- {description} ({len(families)} symbolic families). -/
def {stem}Families : List SymbolicFamily := [
{rows}
]

def {stem}Witness : ℤ := {witness}

theorem {stem}_rejects :
    {stem}Families.all (fun f => f.rejects {stem}Witness) = true := by decide +kernel

theorem {stem}_not_covered :
    ∀ f ∈ {stem}Families, ¬ f.Matches {stem}Witness := by
  intro f hf
  exact f.not_matches_of_rejects _ ((List.all_eq_true.mp {stem}_rejects) f hf)

theorem {stem}_avoids_centers :
    {stem}Families.all (fun f => f.avoidsCenters {stem}Witness) = true := by decide +kernel

theorem {stem}_not_center :
    ∀ f ∈ {stem}Families, ∀ pc ∈ f, ¬ pc.2.IsRayCenter {stem}Witness := by
  intro f hf
  exact f.not_center_of_avoidsCenters _ ((List.all_eq_true.mp {stem}_avoids_centers) f hf)

theorem {stem}_target :
    {stem}Witness % 4 = 2 ∧ {stem}Witness % 5 = 1 ∧
    {stem}Witness % 11 = 6 ∧ {stem}Witness % 17 = 1 := by decide +kernel

/-- The target is not covered even if every exact arrow center is allowed. -/
theorem {stem}_coverage_claim_fails :
    ¬ (∀ z : ℤ, z % 4 = 2 → z % 5 = 1 →
      (∃ f ∈ {stem}Families, f.Matches z) ∨
      ∃ f ∈ {stem}Families, ∃ pc ∈ f, pc.2.IsRayCenter z) := by
  intro h
  rcases h {stem}Witness {stem}_target.1 {stem}_target.2.1 with h | h
  · obtain ⟨f, hf, hm⟩ := h
    exact {stem}_not_covered f hf hm
  · obtain ⟨f, hf, pc, hpc, hc⟩ := h
    exact {stem}_not_center f hf pc hpc hc

end Modulus42
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="check committed output without changing it")
    args = parser.parse_args()
    expressions = o.construction_expressions()
    # These CRT witnesses are fixed proof data; there is no solver at build time.
    specifications = [
        ("EarlyGap.lean", 6, "earlyGap", 3743546626, "Explicit transcription through Owens §3.6"),
        ("Section38Gap.lean", 8, "section38Gap", 60784530626, "Explicit transcription through Owens §3.8"),
    ]
    for filename, count, stem, witness, description in specifications:
        content = render(expressions, count, stem, witness, description)
        path = o.ROOT / "Modulus42" / filename
        if args.check:
            assert path.read_text() == content, f"Generated output differs: {path}"
            print("Checked", path.relative_to(o.ROOT))
        else:
            path.write_text(content)
            print("Wrote", path.relative_to(o.ROOT))


if __name__ == "__main__":
    main()
