#!/usr/bin/env python3
"""Export circuit gates and justified, indexed CNF clause origins to Lean."""
import json
from pathlib import Path
import symbolic_certificate as s

ROOT = Path(__file__).resolve().parent.parent


def table(name, ty, values, chunk=64):
    lines = []
    chunks = [values[i:i + chunk] for i in range(0, len(values), chunk)]
    for index, entries in enumerate(chunks):
        lines += [f"private def {name}Chunk{index} : Array {ty} := #[",
                  "  " + ",\n  ".join(entries), "]", ""]
    groups = [list(range(i, min(i + 64, len(chunks)))) for i in range(0, len(chunks), 64)]
    for group, ids in enumerate(groups):
        lines += [f"private def {name}Group{group} (index : ℕ) : Option {ty} :=",
                  f"  match (index / {chunk}) % 64 with"]
        lines += [f"  | {j} => {name}Chunk{chunk_id}[index % {chunk}]?" for j, chunk_id in enumerate(ids)]
        lines += ["  | _ => none", ""]
    lines += [f"def {name} (index : ℕ) : Option {ty} :=", f"  match index / {chunk * 64} with"]
    lines += [f"  | {i} => {name}Group{i} index" for i in range(len(groups))]
    lines += ["  | _ => none", ""]
    return lines


def main():
    data = json.loads((ROOT / "tmp/circuit/All.json").read_text())
    nodes = data["nodes"]
    atoms = {int(p): xs for p, xs in data["atoms"].items()}
    atom_vars = {}
    next_var = len(nodes) + 1
    for p, xs in atoms.items():
        atom_vars[p] = list(range(next_var, next_var + len(xs)))
        next_var += len(xs)
    gates = []
    for index, node in enumerate(nodes):
        if index < 2: continue
        kind = node[0]
        if kind == "selector":
            selector = s.Selector(**node[1])
            children = [atom_vars[selector.p][i] for i, x in enumerate(atoms[selector.p]) if selector.matches(x)]
            kind = "or"
        else:
            children = [i + 1 for i in node[1]]
        gates.append((index + 1, kind, children))
    origins = [".falsity", ".truth"]
    clauses = [[-1], [2]]
    for domain, xs in enumerate(atom_vars.values()):
        origins.append(f".domain {domain}")
        clauses.append(xs)
    for index, (output, kind, children) in enumerate(gates):
        if kind == "or":
            local = [[-output] + children] + [[output, -x] for x in children]
        else:
            local = [[output] + [-x for x in children]] + [[-output, x] for x in children]
        origins += [f".gate {index} {j}" for j in range(len(local))]
        clauses += local
    target, cover, allowed = (data[k] + 1 for k in ("target", "cover", "allowed"))
    origins += [".target", ".cover", ".allowed"]
    clauses += [[target], [-cover], [-allowed]]
    parsed = [[int(x) for x in line.split()[:-1]] for line in (ROOT / "tmp/circuit/All.cnf").read_text().splitlines() if not line.startswith(("p", "c"))]
    assert parsed == clauses
    lines = ["import Modulus40.CircuitCoverage", "", "/-! Generated by scripts/export_circuit_lean.py.",
             "Circuit gates and each initial CNF clause's local semantic justification. -/", "",
             "namespace Modulus40", "", "set_option maxRecDepth 100000", "set_option maxHeartbeats 0", ""]
    gate_values = [f"({output}, .{'disjunction' if kind == 'or' else 'conjunction'} [{', '.join(map(str, children))}])"
                   for output, kind, children in gates]
    lines += table("constructionCircuitGateLookup", "(ℕ × BooleanGate)", gate_values)
    lines += ["def constructionCircuitGateAt (index : ℕ) : ℕ × BooleanGate :=",
              f"  if index < {len(gates)} then (index + 3, ((constructionCircuitGateLookup index).getD (2, .constant true)).2)",
              "  else (2, .constant true)", ""]
    domains = ["[" + ", ".join(map(str, xs)) + "]" for xs in atom_vars.values()]
    lines += table("constructionCircuitDomainLookup", "(List ℕ)", domains)
    lines += ["def constructionCircuitDomainAt (index : ℕ) : List ℕ :=",
              f"  if index < {len(domains)} then (constructionCircuitDomainLookup index).getD [2] else [2]", ""]
    lines += table("constructionClauseOriginLookup", "CircuitClauseOrigin", origins)
    lines += [f"def constructionCircuitTarget : ℕ := {target}", f"def constructionCircuitCover : ℕ := {cover}",
              f"def constructionCircuitAllowed : ℕ := {allowed}", f"def constructionCNFCount : ℕ := {len(clauses)}", "",
              "def constructionCNFAt (index : ℕ) : Std.Sat.CNF.Clause ℕ :=",
              "  ((constructionClauseOriginLookup index).getD .falsity).clause",
              "    constructionCircuitDomainAt constructionCircuitGateAt",
              "    constructionCircuitTarget constructionCircuitCover constructionCircuitAllowed", "",
              "def constructionCNF : Std.Sat.CNF ℕ :=",
              "  List.ofFn fun index : Fin constructionCNFCount => constructionCNFAt index", "",
              "theorem constructionCircuit_covers_of_unsat",
              "    (hunsat : Std.Sat.CNF.Unsat constructionCNF) (assignment : ℕ → Bool)",
              "    (hfalse : assignment 1 = false) (htrue : assignment 2 = true)",
              "    (hdomains : ∀ i, ∃ v ∈ constructionCircuitDomainAt i, assignment v = true)",
              "    (hgates : ∀ i, assignment (constructionCircuitGateAt i).1 =",
              "      (constructionCircuitGateAt i).2.eval assignment) :",
              "    assignment constructionCircuitCover = true := by",
              "  have h := circuit_origins_unsat_covers constructionCircuitDomainAt constructionCircuitGateAt",
              "    constructionCircuitTarget constructionCircuitCover constructionCircuitAllowed constructionCNFCount",
              "    (fun i => (constructionClauseOriginLookup i).getD .falsity)",
              "    hunsat assignment hfalse htrue hdomains hgates htrue",
              "  simpa [constructionCircuitAllowed, hfalse] using h", "", "end Modulus40", ""]
    out = ROOT / "Modulus40/ConstructionCircuitData.lean"
    out.write_text("\n".join(lines))
    print(f"{len(gates)} gates, {len(origins)} clause origins; {out.stat().st_size:,} bytes")


if __name__ == "__main__": main()
