#!/usr/bin/env python3
"""Pack sorted source groups and pair witnesses into Lean natural literals.

Each record stores a 27-bit prime tag, 6-bit size, 21 bits per source index,
and then 5 bits per separating-coordinate witness in triangular order.
Lookup uses a tree of small arrays, avoiding huge array normalization.
"""
import gzip
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    with gzip.open(ROOT/'data/support-groups.json.gz','rt') as stream:
        data=json.load(stream)
    records=[]
    for tag,sources,codes,witnesses in data['groups']:
        assert len(sources)<=40 and len(witnesses)==len(sources)*(len(sources)-1)//2
        value=tag | len(sources)<<27
        offset=33
        for source in sources:
            assert source < 2**21
            value |= source<<offset
            offset+=21
        for witness in witnesses:
            assert witness<27
            value |= witness<<offset
            offset+=5
        records.append(value)
    path=ROOT/'Modulus40/SupportGroupData.lean'
    lines=['import Modulus40.ConstructionEval','','/-!', '# Packed support groups', '',
           'Generated by `scripts/generate_support_group_data.py`. Each group retains original',
           'construction source indices and an explicit separating coordinate for every pair.',
           'The data are not themselves proofs of the required checks.', '-/','',
           'namespace Modulus40','','set_option maxRecDepth 4096','set_option maxHeartbeats 0','']
    names=[]
    for start in range(0,len(records),64):
        name=f'supportRecordsLeaf{start//64}'
        names.append(name)
        values=records[start:start+64]
        lines += [f'private def {name} : Array ℕ := #[',
                  '  '+',\n  '.join(hex(value) for value in values),']','']
    span=64
    level=0
    while len(names)>1:
        next_names=[]
        for start in range(0,len(names),64):
            name=f'supportRecordsLevel{level}_{start//64}'
            next_names.append(name)
            lines += [f'private def {name} (index : ℕ) : ℕ :=',f'  match index / {span} with']
            for position,child in enumerate(names[start:start+64]):
                term=f'({child}[index % {span}]?).getD 0' if level==0 else f'{child} (index % {span})'
                lines.append(f'  | {position} => {term}')
            lines += ['  | _ => 0','']
        names=next_names
        span*=64
        level+=1
    lines += [f'def constructionSupportGroupCount : ℕ := {len(records)}','',
              f'def constructionSupportRecord : ℕ → ℕ := {names[0]}','',
              '/-- Sorted positive-prime support signature for a group. -/',
              'def constructionSupportTags (group : Fin constructionSupportGroupCount) : ℕ :=',
              '  constructionSupportRecord group.val % 2 ^ 27','',
              '/-- Number of source patterns in a group. -/',
              'def constructionSupportSizes (group : Fin constructionSupportGroupCount) : ℕ :=',
              '  (constructionSupportRecord group.val >>> 27) % 64','',
              '/-- Original AST source index of a group member. -/',
              'def constructionSupportSources (group : Fin constructionSupportGroupCount)',
              '    (member : Fin (constructionSupportSizes group)) : Fin constructionCount :=',
              '  let value := (constructionSupportRecord group.val >>> (33 + 21 * member.val)) % 2 ^ 21',
              '  ⟨value % constructionCount, Nat.mod_lt _ (by rw [constructionCount_eq]; decide)⟩','',
              '/-- The supplied separating coordinate, for members `a < b`. -/',
              'def constructionSupportWitnesses (group : Fin constructionSupportGroupCount)',
              '    (a b : Fin (constructionSupportSizes group)) : Fin 27 :=',
              '  let pair := b.val * (b.val - 1) / 2 + a.val',
              '  let shift := 33 + 21 * constructionSupportSizes group + 5 * pair',
              '  ⟨((constructionSupportRecord group.val >>> shift) % 32) % 27, Nat.mod_lt _ (by decide)⟩','',
              'end Modulus40','']
    path.write_text('\n'.join(lines))
    print(len(records),'packed groups;',path.stat().st_size,'Lean bytes;',level,'lookup levels',flush=True)


if __name__=='__main__':
    main()
