#!/usr/bin/env python3
"""Generate explicit Lean data from the checked transcription of sections 4.1-4.4.

The generated theorem proofs use Lean's kernel evaluator, not this Python program.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / 'data/sections-4.1-4.4.json'
OUT = ROOT / 'Modulus40/InitialData.lean'


def selector(s):
    p, lo, hi = s['p'], s['lo'], s['hi']
    if s['kind'] == 'fixed':
        return f'.fixed ⟨{p ** lo}, {s["residue"]}⟩'
    if hi is not None:
        assert hi == lo
        residue = s['center'] + s['digit'] * p ** (lo - 1)
        return f'.fixed ⟨{p ** lo}, {residue}⟩'
    return f'.ray ⟨{p}, {lo}, {s["center"]}, {s["digit"]}⟩'


def coordinate(s):
    if s is None:
        return '.fixed 0 0'
    if s['kind'] == 'fixed':
        return f'.fixed {s["lo"]} ({s["residue"]})'
    if s['hi'] is not None:
        assert s['hi'] == s['lo']
        residue = s['center'] + s['digit'] * s['p'] ** (s['lo'] - 1)
        return f'.fixed {s["lo"]} ({residue})'
    return f'.ray {s["lo"]} ({s["center"]}) {s["digit"]}'


def main():
    data = json.loads(DATA.read_text())
    families = data['families']
    lines = ['import Modulus40.Compile', 'import Modulus40.IndexedCore', '', '/-!',
             '# Explicit data for sections 4.1–4.4', '',
             'Generated by `scripts/generate_initial_lean.py` from the transcribed paper.',
             'This is a partial certificate, with holes subsequently filled in the paper.',
             '-/', '', 'namespace Modulus40', '', 'set_option maxRecDepth 100000',
             'set_option maxHeartbeats 0', '', 'def initialPrimes : Fin 4 → ℕ := ![2, 3, 5, 7]', '',
             'def initialPatterns : Certificate := [']
    for i, f in enumerate(families):
        lines.append('  -- ' + str(i) + ': section ' + f['source'])
        lines.append('  [' + ', '.join(selector(s) for s in f['selectors']) + ']' + (',' if i + 1 < len(families) else ''))
    lines += [']', '', f'def initialBoxes : Fin {len(families)} → SupportBox 4 := ![']
    for i, f in enumerate(families):
        ss = {s['p']: s for s in f['selectors']}
        parts = []
        for p in (2, 3, 5, 7):
            s = ss.get(p)
            if s is None:
                parts.append('.fixed 0')
            elif s['hi'] is None:
                parts.append(f'.ray {s["lo"]}')
            else:
                assert s['hi'] == s['lo']
                parts.append(f'.fixed {s["lo"]}')
        lines.append('  ![' + ', '.join(parts) + ']' + (',' if i + 1 < len(families) else ''))
    lines += [']', '', f'def initialPrimePatterns : Fin {len(families)} → PrimePattern 4 := ![']
    for i, f in enumerate(families):
        ss = {s['p']: s for s in f['selectors']}
        lines.append('  ![' + ', '.join(coordinate(ss.get(p)) for p in (2, 3, 5, 7)) + ']' +
                     (',' if i + 1 < len(families) else ''))
    lines += [']', '', 'theorem initialPatterns_valid : ∀ ss ∈ initialPatterns, ss.Valid := by',
              '  decide', '',
              'theorem initialPrimes_prime : ∀ i, (initialPrimes i).Prime := by decide', '',
              'theorem initialPrimes_injective : Function.Injective initialPrimes := by decide', '',
              'theorem initialBoxes_match : ∀ i j,',
              '    initialBoxes i j = primePatternBoxes initialPrimePatterns i j := by decide', '',
              'theorem initialBoxes_separated : ∀ i j, i ≠ j →',
              '    (primePatternBoxes initialPrimePatterns i).Separated',
              '      (primePatternBoxes initialPrimePatterns j) := by decide', '',
              'theorem initialBoxes_minimum : ∀ i, 40 ≤ supportModulus initialPrimes',
              '    (fun j => (initialPrimePatterns i j).interval.lo) := by decide', '',
              '/-- Actual ordinary classes in the first four sections have no repeated modulus,',
              'at every finite truncation depth. This does not assert they cover all integers. -/',
              'theorem initialCore_distinct (bound : ℕ) :',
              '    DistinctModuli (indexedCore initialPrimes initialPrimes_prime',
              '      initialPrimes_injective initialPrimePatterns bound) :=',
              '  indexedCore_distinct initialPrimes initialPrimes_prime initialPrimes_injective',
              '    initialPrimePatterns initialBoxes_separated', '',
              '/-- The modulus 40 occurs as 4 (mod 8) intersected with 1 (mod 5). -/',
              'theorem initialCore_minimum (bound : ℕ) (hbound : 3 ≤ bound) :',
              '    HasSmallestModulus (indexedCore initialPrimes initialPrimes_prime',
              '      initialPrimes_injective initialPrimePatterns bound) 40 := by',
              '  constructor',
              '  · intro c hc',
              '    exact indexedCore_modulus_lower_bound initialPrimes initialPrimes_prime',
              '      initialPrimes_injective initialPrimePatterns initialBoxes_minimum hc',
              '  · apply indexedCore_attains initialPrimes initialPrimes_prime initialPrimes_injective',
              '      initialPrimePatterns ⟨6, by decide⟩ ![3, 0, 1, 0]',
              '    · decide',
              '    · intro j; fin_cases j <;> simp <;> omega',
              '    · decide', '', 'end Modulus40', '']
    OUT.write_text('\n'.join(lines))
    print(f'Generated {OUT} ({len(families)} patterns)')


if __name__ == '__main__':
    main()
